// ==========================================================================
// Project:   Klb
// Copyright: ©2009 Kiva Microfunds
// Licensed under MIT License Terms (see license.js)
// ==========================================================================
/*globals Klb */

// Place strings you want to localize here.  In your app, use the key and
// localize it using "key string".loc().  HINT: For your key names, use the
// english string with an underscore in front.  This way you can still see
// how your UI will look and you'll notice right away when something needs a
// localized string added to this file!
//
SC.stringsFor('Deutsch', {
  // "_String Key": "Localized String"
	"__INTL__":"de",

	//// General
	"_KlbTitle": "Kiva auf Deutsch",
	"_OK": "OK",
	"_Edit": "bearbeiten",
	
	//// Primary Sections
	"_About": "Über",
	"_Projects": "Projekte",
	"_Learn_More": "Erfahre mehr",
	"_Register": "Anmelden",
	"_Demo": "Demo",

	"_Choose_A_Loan": "Wähle einen Kredit",
	"_Get started now by finding an entrepreneur and making a loan!":"Beginne hier damit, einen Kreditnehmer auszusuchen!",// dem Du einen Kredit geben möchtest!",
		
	//// Basket
	"_Checkout": "Zur Kasse",

	// sort drop down
	"_Sort_by": "Sortiere nach",
	"_Loan_Amount": "Höhe des Kredits",
	"_Amount_Remaining": "Verbleibender Betrag",
	"_sb:Expiring Soon": "Endet bald",
	"_Most_Recent": "Jüngste Einträge",
	"_List_Grid":"Liste anzeigen",
	"_List":"Liste",
	
	/// Sidebar
	'_Explore':'Erkunden',
	'_Getting Started':'So geht es los',
	'_Browse All Loans':'Alle Kreditanfragen sehen',
	'_Sample Filters':'Beispiel-Filter',
	'_African Farmers':'Afrikanische Bauern',
	'_African Women':'Afrikanische Frauen',
	'_Educational Loans':'Studenten-Darlehen',
	'_Francophone Countries':'Französischsprachige Länder',
	'_Expiring Soon':'Ended bald',
	
	"_Filter Options":"Filter-Optionen",
	"_Search": "Suche (in Kürze)",
  "_Countries": "Länder",
  "_Sectors": "Bereiche",
  "_Gender": "Geschlechter",
  "_Female": "weiblich",
  "_Male": "männlich",
  "_Gender": "Geschlecht",
  "_Sector": "Bereich",
  "_Borrowers": "Kreditgeber pro Kredit",
  "_Partner_Rating": "Schlechteste Partner-Bewertung",
  "_Groups": "Gruppen",
  "_Individuals": "Einzelpersonen",
  "_Reset": "Zurücksetzen",
  "_Save": "Speichern",
  "_All": "Alle",

	// Countries Popup
	"_Choose Countries":"Länder auswählen",

	// Sectors Popup
	"_Choose Sectors":"Bereiche auswählen",
	
	// Results area
	"_loans found":"Gefundene Kredite",
	"_loan found":"Gefundener Kredit",

	"_Finding Available Loans":"Suche verfügbare Kreditanfragen…",
	"_No Loans Matched Your Criteria":"Keine Kreitanfragen gefunden, die Deinen Vorgaben entsprechen",
	"_Please choose another filter or change your filter options.":"Bitte wähle einen anderen Filter oder ändere Deine Such-Vorgaben.",
	
	//loan_list_item"
	"_Loan_Use":"Kredit benötigt für",
	"_Country": "Land",
	"_Rating": "Bewertung",
	"_Needed_Out_Of":"benötigt von insgesamt",
	"_Lend $25":"Leihe $25",
	
	// Countries
	"_AFGHANISTAN":"Afghanistan",
	"_ÅLAND_ISLANDS":"Åland-Inseln",
	"_ALBANIA":"Albanien",
	"_ALGERIA":"Algerien",
	"_AMERICAN_SAMOA":"Amerikanisch-Samoa",
	"_ANDORRA":"Andorra",
	"_ANGOLA":"Angola",
	"_ANGUILLA":"Anguilla",
	"_ANTARCTICA":"Antarktis",
	"_ANTIGUA_AND BARBUDA":"Antigua und Barbuda",
	"_ARGENTINA":"Argentinien",
	"_ARMENIA":"Armenien",
	"_ARUBA":"Aruba",
	"_AUSTRALIA":"Australien",
	"_AUSTRIA":"Österreich",
	"_AZERBAIJAN":"Aserbaidschan",
	"_BAHAMAS":"Bahamas",
	"_BAHRAIN":"Bahrain",
	"_BANGLADESH":"Bangladesch",
	"_BARBADOS":"Barbados",
	"_BELARUS":"Weißrussland",
	"_BELGIUM":"Belgien",
	"_BELIZE":"Belize",
	"_BENIN":"Benin",
	"_BERMUDA":"Bermuda",
	"_BHUTAN":"Bhutan",
	"_BOLIVIA,_PLURINATIONAL STATE OF":"Bolivien",
	"_BOSNIA_AND HERZEGOVINA":"Bosnien und Herzegowina",
	"_BOTSWANA":"Botswana",
	"_BOUVET_ISLAND":"Bouvetinsel",
	"_BRAZIL":"Brasilien",
	"_BRITISH_INDIAN OCEAN TERRITORY":"Britisches Territorium im Indischen Ozean",
	"_BRUNEI_DARUSSALAM":"Brunei",
	"_BULGARIA":"Bulgarien",
	"_BURKINA_FASO":"Burkina Faso",
	"_BURUNDI":"Burundi",
	"_CAMBODIA":"Kambodscha",
	"_CAMEROON":"Kamerun",
	"_CANADA":"Kanada",
	"_CAPE_VERDE":"Kap Verde",
	"_CAYMAN_ISLANDS":"Kaimaninseln",
	"_CENTRAL_AFRICAN REPUBLIC":"Zentral-Afrikanische Republik",
	"_CHAD":"Tschad",
	"_CHILE":"Chile",
	"_CHINA":"China",
	"_CHRISTMAS_ISLAND":"Weihnachtsinsel",
	"_COCOS_(KEELING)_ISLANDS":"Kokosinseln",
	"_COLOMBIA":"Kolumbien",
	"_COMOROS":"Komoren",
	"_CONGO":"Kongo",
	"_CONGO,_THE DEMOCRATIC REPUBLIC OF THE":"Kongo",
	"_COOK_ISLANDS":"Cookinseln",
	"_COSTA_RICA":"Costa Rica",
	"_CÔTE_D'IVOIRE":"Elfenbeinküste",
	"_CROATIA":"Kroatien",
	"_CUBA":"Kuba",
	"_CYPRUS":"Zypern",
	"_CZECH_REPUBLIC":"Tschechische Republik",
	"_DENMARK":"Dänemark",
	"_DJIBOUTI":"Djibouti",
	"_DOMINICA":"Dominica",
	"_DOMINICAN_REPUBLIC":"Dominikanische Republik",
	"_ECUADOR":"Ecuador",
	"_EGYPT":"Ägypten",
	"_EL_SALVADOR":"El Salvador",
	"_EQUATORIAL_GUINEA":"Äquatorialguinea",
	"_ERITREA":"Eritrea",
	"_ESTONIA":"Estland",
	"_ETHIOPIA":"Äthiopien",
	"_FALKLAND_ISLANDS_(MALVINAS)":"Falkland-Inseln",
	"_FAROE_ISLANDS":"Färöer",
	"_FIJI":"Fiji",
	"_FINLAND":"Finnland",
	"_FRANCE":"Frankreich",
	"_FRENCH_GUIANA":"Französisch-Guayana",
	"_FRENCH_POLYNESIA":"Französisch-Polynesien",
	"_FRENCH_SOUTHERN TERRITORIES":"Französisches Süd-Territorium",
	"_GABON":"Gabon",
	"_GAMBIA":"Gambia",
	"_GEORGIA":"Georgien",
	"_GERMANY":"Deutschland",
	"_GHANA":"Ghana",
	"_GIBRALTAR":"Gibraltar",
	"_GREECE":"Griechenland",
	"_GREENLAND":"Grönland",
	"_GRENADA":"Grenada",
	"_GUADELOUPE":"Guadeloupe",
	"_GUAM":"Guam",
	"_GUATEMALA":"Guatemala",
	"_GUERNSEY":"Guernsey",
	"_GUINEA":"Guinea",
	"_GUINEA-BISSAU":"Guinea-Bissau",
	"_GUYANA":"Guyana",
	"_HAITI":"Haiti",
	"_HEARD_ISLAND AND MCDONALD ISLANDS":"Heard- und McDonaldinseln",
	"_HONDURAS":"Honduras",
	"_HONG_KONG":"Hong Kong",
	"_HUNGARY":"Ungarn",
	"_ICELAND":"Island",
	"_INDIA":"Indien",
	"_INDONESIA":"Indonesien",
	"_IRAN,_ISLAMIC REPUBLIC OF":"Iran",
	"_IRAQ":"Irak",
	"_IRELAND":"Irland",
	"_ISLE_OF MAN":"Isle Of Man",
	"_ISRAEL":"Israel",
	"_ITALY":"Italien",
	"_JAMAICA":"Jamaika",
	"_JAPAN":"Japan",
	"_JERSEY":"Jersey",
	"_JORDAN":"Jordanien",
	"_KAZAKHSTAN":"Kasachstan",
	"_KENYA":"Kenia",
	"_KIRIBATI":"Kiribati",
	"_KOREA,_DEMOCRATIC PEOPLE'S REPUBLIC OF":"Süd-Korea",
	"_KOREA,_REPUBLIC OF":"Nord-Korea",
	"_KUWAIT":"Kuwait",
	"_KYRGYZSTAN":"Kirgisistan",
	"_LAO_PEOPLE'S DEMOCRATIC REPUBLIC":"Laos",
	"_LATVIA":"Lettland",
	"_LEBANON":"Libanon",
	"_LESOTHO":"Lesotho",
	"_LIBERIA":"Liberia",
	"_LIBYAN_ARAB JAMAHIRIYA":"Libysches arabisches Jamahiriya",
	"_LIECHTENSTEIN":"Liechtenstein",
	"_LITHUANIA":"Litauen",
	"_LUXEMBOURG":"Luxemburg",
	"_MACAO":"Macao",
	"_MACEDONIA,_THE FORMER YUGOSLAV REPUBLIC OF":"Mazedonien",
	"_MADAGASCAR":"Madagaskar",
	"_MALAWI":"Malawi",
	"_MALAYSIA":"Malaysia",
	"_MALDIVES":"Maldiven",
	"_MALI":"Mali",
	"_MALTA":"Malta",
	"_MARSHALL_ISLANDS":"Marshallinseln",
	"_MARTINIQUE":"Martinique",
	"_MAURITANIA":"Mauritanien",
	"_MAURITIUS":"Mauritius",
	"_MAYOTTE":"Mayotte",
	"_MEXICO":"Mexiko",
	"_MICRONESIA,_FEDERATED STATES OF":"Micronesien",
	"_MOLDOVA,_REPUBLIC OF":"Moldovien",
	"_MONACO":"Monaco",
	"_MONGOLIA":"Mongolei",
	"_MONTENEGRO":"Montenegro",
	"_MONTSERRAT":"Montserrat",
	"_MOROCCO":"Morokko",
	"_MOZAMBIQUE":"Mosambik",
	"_MYANMAR":"Myanmar",
	"_NAMIBIA":"Namibia",
	"_NAURU":"Nauru",
	"_NEPAL":"Nepal",
	"_NETHERLANDS":"Niederlande",
	"_NETHERLANDS_ANTILLES":"Niederländische Antillen",
	"_NEW_CALEDONIA":"Neukaledonien",
	"_NEW_ZEALAND":"Neuseeland",
	"_NICARAGUA":"Nicaragua",
	"_NIGER":"Niger",
	"_NIGERIA":"Nigeria",
	"_NIUE":"Niue",
	"_NORFOLK_ISLAND":"Norfolkinsel",
	"_NORTHERN_MARIANA ISLANDS":"Nördliche Marianen",
	"_NORWAY":"Norwegen",
	"_OMAN":"Oman",
	"_PAKISTAN":"Pakistan",
	"_PALAU":"Palau",
	"_PALESTINIAN_TERRITORY, OCCUPIED":"Palästina",
	"_PANAMA":"Panama",
	"_PAPUA_NEW GUINEA":"Papua-Neuguinea",
	"_PARAGUAY":"Paraguay",
	"_PERU":"Peru",
	"_PHILIPPINES":"Philippinen",
	"_PITCAIRN":"Pitcairn",
	"_POLAND":"Polen",
	"_PORTUGAL":"Portugal",
	"_PUERTO_RICO":"Puerto Rico",
	"_QATAR":"Katar",
	"_RÉUNION":"Reunion",
	"_ROMANIA":"Rumänien",
	"_RUSSIAN_FEDERATION":"Russische Föderation",
	"_RWANDA":"Ruanda",
	"_SAINT_BARTHÉLEMY":"Sankt Bartholomäus",
	"_SAINT_HELENA, ASCENSION AND TRISTAN DA CUNHA":"St. Helena, Ascension und Tristan da Cunha",
	"_TTS_AND NEVIS":"St. Kitts und Nevis",
	"_SAINT_LUCIA":"St. Lucia",
	"_SAINT_MARTIN":"Saint-Martin",
	"_SAINT_PIERRE AND MIQUELON":"Saint-Pierre  und Miquelon",
	"_SAINT_VINCENT AND THE GRENADINES":"St. Vincent  und die Grenadinen",
	"_SAMOA":"Samoa",
	"_SAN_MARINO":"San Marino",
	"_SAO_TOME AND PRINCIPE":"Sao-Tome und Principe",
	"_SAUDI_ARABIA":"Saudi-Arabien",
	"_SENEGAL":"Senegal",
	"_SERBIA":"Serbien",
	"_SEYCHELLES":"Seychellen",
	"_SIERRA_LEONE":"Sierra Leone",
	"_SINGAPORE":"Singapur",
	"_SLOVAKIA":"Slowakei",
	"_SLOVENIA":"Slowenien",
	"_SOLOMON_ISLANDS":"Salomonen",
	"_SOMALIA":"Somalia",
	"_SOUTH_AFRICA":"Südafrika",
	"_SOUTH_GEORGIA AND THE SOUTH SANDWICH ISLANDS":"Südgeorgien und die Südlichen Sandwichinseln",
	"_SPAIN":"Spanien",
	"_SRI_LANKA":"Sri Lanka",
	"_SUDAN":"Sudan",
	"_SURINAME":"Suriname",
	"_SVALBARD_AND JAN MAYEN":"Svalbard und Jan Mayen Inseln",
	"_SWAZILAND":"Swaziland",
	"_SWEDEN":"Schweden",
	"_SWITZERLAND":"Schweiz",
	"_SYRIAN_ARAB REPUBLIC":"Syrien",
	"_TAIWAN,_PROVINCE OF CHINA":"Taiwan",
	"_TAJIKISTAN":"Tadschikistan",
	"_TANZANIA,_UNITED_REPUBLIC_OF":"Tansania",
	"_THAILAND":"Thailand",
	"_TIMOR-LESTE":"Osttimor",
	"_TOGO":"Togo",
	"_TOKELAU":"Tokelau",
	"_TONGA":"Tonga",
	"_TRINIDAD_AND TOBAGO":"Trinidad und Tobago",
	"_TUNISIA":"Tunesien",
	"_TURKEY":"Turkei",
	"_TURKMENISTAN":"Turkmenistan",
	"_TURKS_AND CAICOS ISLANDS":"Turks- und Caicosinseln",
	"_TUVALU":"Tuvalu",
	"_UGANDA":"Uganda",
	"_UKRAINE":"Ukraine",
	"_UNITED_ARAB EMIRATES":"Vereinigte Arabische Emirate",
	"_UNITED_KINGDOM":"Vereinigtes Königreich",
	"_UNITED_STATES":"Vereinigte Staaten",
	"_UNITED_STATES MINOR OUTLYING ISLANDS":"Kleinere Inselbesitzungen der Vereinigten Staaten",
	"_URUGUAY":"Uruguay",
	"_UZBEKISTAN":"Usbekistan",
	"_VANUATU":"Vanuatu",
	"_VATICAN_CITY STATE":"Vatikanstadt",
	"_VENEZUELA,_BOLIVARIAN REPUBLIC OF":"Venezuela",
	"_VIET_NAM":"Vietnam",
	"_VIRGIN_ISLANDS, BRITISH":"Britische Jungferninseln",
	"_VIRGIN_ISLANDS, U.S.":"Amerikanische Jungferninseln",
	"_WALLIS_AND FUTUNA":"Wallis und Futuna",
	"_WESTERN_SAHARA":"Westsahara",
	"_YEMEN":"Jemen",
	"_ZAMBIA":"Sambia",
	"_ZIMBABWE":"Simbabwe",
	"_SOUTHERN_SUDAN_TERRITORY,_PROVISIONAL":"Südsudan",
	
	// Activities
	"_Agriculture":"Landwirtschaft",
	"_Air Conditioning":"Klimaanlagen",
	"_Animal Sales":"Tier-Verkauf",
	"_Arts":"Kunst",
	"_Auto Repair":"Auto-Reparaturen",
	"_Bakery":"Bäckerei",
	"_Balut-Making":"Balut-Herstellung",
	"_Barber Shop":"Frisör-Laden",
	"_Beauty Salon":"Schönheits-Salon",
	"_Bicycle Repair":"Fahrrad-Reparaturen",
	"_Bicycle Sales":"Fahrrad-Verkauf",
	"_Biofuels":"Bio-Diesel",
	"_Blacksmith":"Schmied",
	"_Bookbinding":"Buchbinder",
	"_Bookstore":"Buchhandel",
	"_Bricks":"Ziegelei",
	"_Butcher Shop":"Fleischerei",
	"_Cafe":"Cafe",
	"_Call Center":"Call Center",
	"_Carpentry":"Zimmerei",
	"_Catering":"Catering",
	"_Cattle":"Viehzucht",
	"_Cement":"Zement",
	"_Cereals":"Getreide",
	"_Charcoal Sales":"Kohle-Verkauf",
	"_Cheese Making":"Käserei",
	"_Child Care":"Kinderbetreuung",
	"_Cloth & Dressmaking Supplies":"Schneiderei-Zubehör",
	"_Clothing":"Schneider",
	"_Clothing Sales":"Bekleidungs-Verkauf",
	"_Cobbler":"Schuster",
	"_Computers":"Computer",
	"_Construction":"Bauwesen",
	"_Construction Supplies":"Bau-Ausstattung",
	"_Consumer Goods":"Gebrauchsgüter",
	"_Cosmetics Sales":"Kosmetik-Verkauf",
	"_Crafts":"Handwerk",
	"_Dairy":"Molkerei",
	"_Decorations Sales":"Verkauf von Dekorationsartikeln",
	"_Dental":"Zahn-Zubehör",
	"_Electrical Goods":"Elektrische Produkte",
	"_Electrician":"Elektriker",
	"_Electronics Repair":"Reparatur von Elektronik",
	"_Electronics Sales":"Verkauf von Elektronik",
	"_Embroidery":"Stickerei",
	"_Energy Efficiency":"Energieeffizienz",
	"_Entertainment":"Unterhaltung",
	"_Farm Supplies":"Zubehör für die Landwirtschaft",
	"_Farming":"Landwirtschaft",
	"_Film":"Film",
	"_Fish Selling":"Fisch-Verkauf",
	"_Fishing":"Fischerei",
	"_Flowers":"Blumen",
	"_Food":"Nahrungsmittel",
	"_Food Market":"Nahrungsmittel-Markt",
	"_Food Production/Sales":"Produktion und Verkauf von Nahrungsmiteln",
	"_Food Stall":"Imbissstand",
	"_Fruits & Vegetables":"Früchte und Gemüse",
	"_Fuel/Firewood":"Benzin und Brennholz",
	"_Funeral Expenses":"Beerdigungskosten",
	"_Furniture Making":"Möbel-Herstellung",
	"_Games":"Spiele",
	"_General Store":"Gemischtwarenladen",
	"_Goods Distribution":"Warenauslieferung",
	"_Green":"Grün",
	"_Grocery Store":"Lebensmittelgeschäft",
	"_Hardware":"Haushaltswaren",
	"_Health":"Gesundheit",
	"_Home Appliances":"Haushaltsgeräte",
	"_Home Products Sales":"Verkauf von Produkten rund ums Haus",
	"_Hotel":"Hotel",
	"_Internet Cafe":"Internet-Cafe",
	"_Jewelry":"Schmuck",
	"_Knitting":"Strickerei",
	"_Land Rental":"Verpachtung von Land",
	"_Laundry":"Wäscherei",
	"_Liquor Store / Off-License":"Spirituosen-Verkauf",
	"_Livestock":"Nutztiere",
	"_Machine Shop":"Verkauf von Maschinen",
	"_Machinery Rental":"Vermietung von Maschinen",
	"_Manufacturing":"Produktion",
	"_Medical Clinic":"Krankenhaus",
	"_Metal Shop":"Metall-Handel",
	"_Milk Sales":"Milch-Verkauf",
	"_Mobile Phones":"Mobiltelefone",
	"_Motorcycle Repair":"Motorrad-Reperatur",
	"_Motorcycle Transport":"Motorrad-Transporte",
	"_Movie Tapes and DVDs":"Videos und DVDs",
	"_Music Discs and Tapes":"Musik-Kassetten und CDs",
	"_Musical Instruments":"Musik-Instrumente",
	"_Musical Performance":"Musik-Vorstellungen",
	"_Natural Medicines":"Natürliche Medizin",
	"_Office Supplies":"Büro-Ausstattungen",
	"_Paper Sales":"Papier-Verkauf",
	"_Party Supplies":"Party-Ausstattungen",
	"_Patchwork":"Flickarbeiten",
	"_Perfumes":"Parfüme",
	"_Family Education Expenses":"Ausgaben für die Weiterbildung",
	"_Personal Education Expenses":"Ausgaben für die persönliche Weiterbildung",
	"_Personal Student Loan":"Studenten-Darlehen",
	"_Personal Housing Expenses":"Ausgaben für die Wohnung",
	"_Personal Medical Expenses":"Persönliche medizinische Ausgaben",
	"_Personal Products Sales":"Verkauf persönlicher Produkte",
	"_Personal Purchases":"Persönliche Verkäufe",
	"_Pharmacy":"Apotheke",
	"_Phone Accessories":"Telefon-Zubehör",
	"_Phone Repair":"Telefon-Reparaturen",
	"_Phone Use Sales":"Verkauf von Telefonen",
	"_Photography":"Fotografie",
	"_Pigs":"Schweine",
	"_Plastics Sales":"Verkauf von Plastikwaren",
	"_Poultry":"Geflügel",
	"_Printing":"Druckerei",
	"_Property":"Eigentum",
	"_Pub":"Kneipe",
	"_Quarrying":"Abbau",
	"_Recycling":"Recycling",
	"_Religious Articles":"Religiöse Waren",
	"_Restaurant":"Restaurant",
	"_Retail":"Wiederverkauf",
	"_Rickshaw":"Rikscha",
	"_Secretarial Services":"Sekretariats-Dienstleistungen",
	"_Services":"Dienstleistungen",
	"_Sewing":"Schneiderei",
	"_Shoe Sales":"Schuh-Verkauf",
	"_Soft Drinks":"Alkoholfreie  Getränke",
	"_Solar Power":"Sonnenkraft",
	"_Souvenir Sales":"Verkauf von Souvenirs",
	"_Spare Parts":"Ersatzteile",
	"_Sporting Good Sales":"Verkauf von Sportartikeln",
	"_Tailoring":"Schneiderei",
	"_Taxi":"Taxi",
	"_Teaching and Schools":"Schule und Ausbildung",
	"_Textiles":"Textilien",
	"_Timber Sales":"Holzverkauf",
	"_Tourism":"Tourismus",
	"_Transportation":"Transportwesen",
	"_Traveling Sales":"Verkauf von Reiseausstattung",
	"_Upholstery":"Polsterei",
	"_Used Clothing":"Gebrauchte Kleidung",
	"_Utilities":"Betriebsmittel",
	"_Vehicle":"Fahrzeug",
	"_Vehicle Repairs":"Fahrzeug-Reparaturen",
	"_Veterinary Sales":"Verkäufe für Tierärzte",
	"_Waste Management":"Abfallwirtschaft",
	"_Water Distribution":"Wasser-Verteilung",
	"_Weaving":"Weben",
	"_Wedding Expenses":"Hochzeitsausstattungen",
	"_Well digging":"schürfen",
	"_Wholesale":"Großhandel",
	
	// Sectors
	"_Agriculture":"Landwirtschaft",
	"_Arts":"Kunst",
	"_Clothing":"Bekleidung",
	"_Construction":"Bauwesen",
	"_Education":"Bildung",
	"_Entertainment":"Unterhaltung",
	"_Food":"Ernährung",
	"_Green":"Ökologie",
	"_Health":"Gesundheit",
	"_Housing":"Wohnungswesen",
	"_Manufacturing":"Produktion",
	"_Personal_Use":"Artikel zum persönlichen Bedarf",
	"_Retail":"Wiederverkauf",
	"_Services":"Dienstleistungen",
	"_Transportation":"Transport",
	"_Wholesale":"Großhandel",
	

	//////////////////////////////////////////////
	// PREHOME
	
	// Headers
	'_The Situation':'Die Situation',
	'_In Numbers':'In Zahlen',
	
	// Captions
	'_something about why to click the browse CTA':'',
	'_Kiva. Make a loan, change a life.':'Kiva. Gib einen Kredit, verändere ein Leben.',

	// Borrower Story
	'_An entrepreneur needs a loan to grow her business':'Ein Kreditnehmer muss sein Geschäft erweitern',
	'_Kiva works with local partners who specialize in microcredit':'Kiva arbeitet mit lokalen Partnern im Bereich der Mikrokredite',
	'_People from all over the world become lenders, helping in big ways with small amounts of money':'Menschen aus aller Welt werden Kreditgeber. Sie unterstützen große Projekte mit wenig Geld',

	// Lender Story
	'_Make the choice to change a life':'Wähle ein Projekt, um ein Leben zu verändern',
	'_Get repaid':'Werde ausbezahlt',
	'_Become part of the Kiva community':'Werde ein Teil der Kiva-Gemeinschaft',
	
	//////////////////////////////////////////////
	// ABOUT
	
	// Headers
	'_How Microfinance Began':'Wie die Mikro-Finanzierung begann',
	'_What Is Kiva?':'Was ist Kiva?',
	'_Why Kiva en Français?':'Warum Kiva auf Deutsch?',
	'_Contact':'Kontakt',
	'_Our Partners':'Unsere Partner',

	// Figures
	'_in loans':'Kredite gegeben',
	'_entrepreneurs helped':'Kreditnehmern geholfen',
	'_countries':'Länder',
	'_partners':'Partner',

	// Captions
	'_Kiva connects people through lending to alleviate poverty.':'Kiva verbindet Menschen, um Armut zu vermindern.',
	'*about_captionYunus1':'“Gib einem Mann einen Fisch und er kann einen Tag essen… Lehre ihn zu fischen und er kann sich ein Leben lang ernähren.”',
	'*about_captionYunus2':'Aber was, wenn er sich kein Netz leisten kann?',

	'*mfHow_para_1':"Microfinanzierung wurde in Bangladesh vom Wirtschaftsprofessor Muhammad Yunus entwickelt, der 2006 den Friedens-Nobelpreis erhielt.",
	'*mfHow_para_2':"Der Grundgedanke ist, jenen Kreditnehmern kleine Kredite zur Verfügung zu stellen, die keine Kredite der traditionellen Banken erhalten.",
	'*mfHow_para_3':"Millionen von Menschen wurde es so ermöglicht, sich selbst aus der Armut zu befreien, ihre Geschäfte und ihren Besitz auszubauen.",
	'*mfHow_para_4':"Diese große soziale Innovation wird nun auch in anderen Entwicklungsländern und Gebieten in ähnlicher Lage bekannter.",
	
	'*kivaWhat_para_1':"Kiva.org ist die erste Mikro-Kredit-Institution der Welt, die per Internet arbeitet. Sie finanziert täglich mehr als 500 Projekte.",
	'*kivaWhat_para_2':"Die Erfolgsgeschichte, die 2005 in San Francisco begann, konnte bereits über 100M€ an Krediten in mehr als 55 verschiedene Länder vergeben.",
	'*kivaWhat_para_3':"Kiva hat rigoros mehr als 100 Mikrofinanz-Institute (MFI) ausgewählt, die als Partner vor Ort tätig sind. Gemeinsam erzielten sie eine durchschnittliche Rückzahlungsrate von mehr als 98 Prozent.",
	'*kivaWhat_para_4':"Im Verlauf eines Kredits werden die Kredite schrittweise zurück gezahlt. Die Kreditgeber können sich dann ihr Geld auszahlen lassen oder in weitere Projekte neu investieren.",

	'*kefWhy_para_1':"Die Idee der Mikrokredite soll auch deutschen Nutzern zugänglich gemacht werden. Die Webseite auf deutsch soll es so einfacher machen, die passenden Kiva-Projekte zu finden.",
	'*kefWhy_para_2':"Die Macher der deutschen Webseite sind Freude von Kiva, die ihre Begeisterung weitergeben möchten.",
	'*kefWhy_para_3':"Nachdem Du das Projekt Deiner Wahl gefunden hast, wirst Du zur Kiva-Seite geführt, um Deinen Kredit dort abzuschließen.",

	//////////////////////////////////////////////
	// REGISTER
	
	'*reg_disclaimer_text1':'Um Deinen Kredit zu vergeben, musst Du Dich bei Kiva anmelden. Dieser Vorgang ist auf englisch beschrieben, aber eine Erklärung auf deutsch steht links am Bildschirm bereit. Zu jeder Kreditvergabe wirst Du auf die englische Kiva-Webseite weitergeleitet.',
	'*reg_disclaimer_text2':'Wenn Du bereits ein Benutzerkonto bei Kiva besitzt, kannst Du auf der Kiva-Seite den Kredit direkt vergeben.',
	
	'_Loading Kiva Website':'Lade die Webseite von Kiva…',
	'_Help':'Hilfe',
	'_Use of the english site':'Benutzung der englischen Webseite',
	
	'_Enter your first name':'Gib Deinen Vornamen ein',
	'_Enter your last name':'Gib Deinen Nachnamen ein',
	'_Enter your email address':'Gib Deine E-Mail-Adresse ein',
	'_Re-enter your email address':'Gib Deine E-Mail-Adresse noch einmal ein',
	'_Choose a password between 6 and 12 characters':'Wähle ein Passwort mit 6 bis 12 Zeichen',
	'_Confirm the password you chose':'Bestätige das selbstgewählte Passwort.',
	'_If your friend recommended you to loan on Kiva, please enter their email address so that Kiva can thank them!':'Wenn Dich ein Freund auf Kiva aufmerksam gemacht hat, gib hier seine E-Mail-Adresse ein, damit Kiva ihm danken kann!',

//////////////////////////////////////////////
// DEMOS

	'_The Pedro Story':'Die Geschichte von Pedro',
	'_Demos coming soon… for now, enjoy this introduction to Kiva through the story of Pedro, a farmer in Boliva:':'Demos wird es bald geben… Bis dahin kannst Du Dir als Einführung die Geschichte von Pedro anschauen, einem Farmer in Bolivien:'

}) ;
