// ==========================================================================
// Project:   Klb
// Copyright: ©2009 Kiva Microfunds
// Licensed under MIT License Terms (see license.js)
// ==========================================================================
/*globals Klb */

Klb.COUNTRIES_ISO = [
{"iso_code":"AF",
"iso_name":"AFGHANISTAN",
"name":"_AFGHANISTAN".loc(),
"region":"xx"},
{"iso_code":"AX",
"iso_name":"ÅLAND ISLANDS",
"name":"_ÅLAND_ISLANDS".loc(),
"region":"xx"},
{"iso_code":"AL",
"iso_name":"ALBANIA",
"name":"_ALBANIA".loc(),
"region":"xx"},
{"iso_code":"DZ",
"iso_name":"ALGERIA",
"name":"_ALGERIA".loc(),
"region":"af"},
{"iso_code":"AS",
"iso_name":"AMERICAN SAMOA",
"name":"_AMERICAN_SAMOA".loc(),
"region":"xx"},
{"iso_code":"AD",
"iso_name":"ANDORRA",
"name":"_ANDORRA".loc(),
"region":"xx"},
{"iso_code":"AO",
"iso_name":"ANGOLA",
"name":"_ANGOLA".loc(),
"region":"xx"},
{"iso_code":"AI",
"iso_name":"ANGUILLA",
"name":"_ANGUILLA".loc(),
"region":"xx"},
{"iso_code":"AQ",
"iso_name":"ANTARCTICA",
"name":"_ANTARCTICA".loc(),
"region":"xx"},
{"iso_code":"AG",
"iso_name":"ANTIGUA AND BARBUDA",
"name":"_ANTIGUA_AND BARBUDA".loc(),
"region":"xx"},
{"iso_code":"AR",
"iso_name":"ARGENTINA",
"name":"_ARGENTINA".loc(),
"region":"xx"},
{"iso_code":"AM",
"iso_name":"ARMENIA",
"name":"_ARMENIA".loc(),
"region":"xx"},
{"iso_code":"AW",
"iso_name":"ARUBA",
"name":"_ARUBA".loc(),
"region":"xx"},
{"iso_code":"AU",
"iso_name":"AUSTRALIA",
"name":"_AUSTRALIA".loc(),
"region":"xx"},
{"iso_code":"AT",
"iso_name":"AUSTRIA",
"name":"_AUSTRIA".loc(),
"region":"xx"},
{"iso_code":"AZ",
"iso_name":"AZERBAIJAN",
"name":"_AZERBAIJAN".loc(),
"region":"xx"},
{"iso_code":"BS",
"iso_name":"BAHAMAS",
"name":"_BAHAMAS".loc(),
"region":"xx"},
{"iso_code":"BH",
"iso_name":"BAHRAIN",
"name":"_BAHRAIN".loc(),
"region":"xx"},
{"iso_code":"BD",
"iso_name":"BANGLADESH",
"name":"_BANGLADESH".loc(),
"region":"xx"},
{"iso_code":"BB",
"iso_name":"BARBADOS",
"name":"_BARBADOS".loc(),
"region":"xx"},
{"iso_code":"BY",
"iso_name":"BELARUS",
"name":"_BELARUS".loc(),
"region":"xx"},
{"iso_code":"BE",
"iso_name":"BELGIUM",
"name":"_BELGIUM".loc(),
"region":"xx"},
{"iso_code":"BZ",
"iso_name":"BELIZE",
"name":"_BELIZE".loc(),
"region":"xx"},
{"iso_code":"BJ",
"iso_name":"BENIN",
"name":"_BENIN".loc(),
"region":"xx"},
{"iso_code":"BM",
"iso_name":"BERMUDA",
"name":"_BERMUDA".loc(),
"region":"xx"},
{"iso_code":"BT",
"iso_name":"BHUTAN",
"name":"_BHUTAN".loc(),
"region":"xx"},
{"iso_code":"BO",
"iso_name":"BOLIVIA, PLURINATIONAL STATE OF",
"name":"_BOLIVIA,_PLURINATIONAL STATE OF".loc(),
"region":"xx"},
{"iso_code":"BA",
"iso_name":"BOSNIA AND HERZEGOVINA",
"name":"_BOSNIA_AND HERZEGOVINA".loc(),
"region":"xx"},
{"iso_code":"BW",
"iso_name":"BOTSWANA",
"name":"_BOTSWANA".loc(),
"region":"xx"},
{"iso_code":"BV",
"iso_name":"BOUVET ISLAND",
"name":"_BOUVET_ISLAND".loc(),
"region":"xx"},
{"iso_code":"BR",
"iso_name":"BRAZIL",
"name":"_BRAZIL".loc(),
"region":"xx"},
{"iso_code":"IO",
"iso_name":"BRITISH INDIAN OCEAN TERRITORY",
"name":"_BRITISH_INDIAN OCEAN TERRITORY".loc(),
"region":"xx"},
{"iso_code":"BN",
"iso_name":"BRUNEI DARUSSALAM",
"name":"_BRUNEI_DARUSSALAM".loc(),
"region":"xx"},
{"iso_code":"BG",
"iso_name":"BULGARIA",
"name":"_BULGARIA".loc(),
"region":"xx"},
{"iso_code":"BF",
"iso_name":"BURKINA FASO",
"name":"_BURKINA_FASO".loc(),
"region":"xx"},
{"iso_code":"BI",
"iso_name":"BURUNDI",
"name":"_BURUNDI".loc(),
"region":"xx"},
{"iso_code":"KH",
"iso_name":"CAMBODIA",
"name":"_CAMBODIA".loc(),
"region":"xx"},
{"iso_code":"CM",
"iso_name":"CAMEROON",
"name":"_CAMEROON".loc(),
"region":"xx"},
{"iso_code":"CA",
"iso_name":"CANADA",
"name":"_CANADA".loc(),
"region":"xx"},
{"iso_code":"CV",
"iso_name":"CAPE VERDE",
"name":"_CAPE_VERDE".loc(),
"region":"xx"},
{"iso_code":"KY",
"iso_name":"CAYMAN ISLANDS",
"name":"_CAYMAN_ISLANDS".loc(),
"region":"xx"},
{"iso_code":"CF",
"iso_name":"CENTRAL AFRICAN REPUBLIC",
"name":"_CENTRAL_AFRICAN REPUBLIC".loc(),
"region":"xx"},
{"iso_code":"TD",
"iso_name":"CHAD",
"name":"_CHAD".loc(),
"region":"xx"},
{"iso_code":"CL",
"iso_name":"CHILE",
"name":"_CHILE".loc(),
"region":"xx"},
{"iso_code":"CN",
"iso_name":"CHINA",
"name":"_CHINA".loc(),
"region":"xx"},
{"iso_code":"CX",
"iso_name":"CHRISTMAS ISLAND",
"name":"_CHRISTMAS_ISLAND".loc(),
"region":"xx"},
{"iso_code":"CC",
"iso_name":"COCOS (KEELING) ISLANDS",
"name":"_COCOS_(KEELING) ISLANDS".loc(),
"region":"xx"},
{"iso_code":"CO",
"iso_name":"COLOMBIA",
"name":"_COLOMBIA".loc(),
"region":"xx"},
{"iso_code":"KM",
"iso_name":"COMOROS",
"name":"_COMOROS".loc(),
"region":"xx"},
{"iso_code":"CG",
"iso_name":"CONGO",
"name":"_CONGO".loc(),
"region":"xx"},
{"iso_code":"CD",
"iso_name":"CONGO, THE DEMOCRATIC REPUBLIC OF THE",
"name":"_CONGO,_THE DEMOCRATIC REPUBLIC OF THE".loc(),
"region":"xx"},
{"iso_code":"CK",
"iso_name":"COOK ISLANDS",
"name":"_COOK_ISLANDS".loc(),
"region":"xx"},
{"iso_code":"CR",
"iso_name":"COSTA RICA",
"name":"_COSTA_RICA".loc(),
"region":"xx"},
{"iso_code":"CI",
"iso_name":"CÔTE D'IVOIRE",
"name":"_CÔTE_D'IVOIRE".loc(),
"region":"xx"},
{"iso_code":"HR",
"iso_name":"CROATIA",
"name":"_CROATIA".loc(),
"region":"xx"},
{"iso_code":"CU",
"iso_name":"CUBA",
"name":"_CUBA".loc(),
"region":"xx"},
{"iso_code":"CY",
"iso_name":"CYPRUS",
"name":"_CYPRUS".loc(),
"region":"xx"},
{"iso_code":"CZ",
"iso_name":"CZECH REPUBLIC",
"name":"_CZECH_REPUBLIC".loc(),
"region":"xx"},
{"iso_code":"DK",
"iso_name":"DENMARK",
"name":"_DENMARK".loc(),
"region":"xx"},
{"iso_code":"DJ",
"iso_name":"DJIBOUTI",
"name":"_DJIBOUTI".loc(),
"region":"xx"},
{"iso_code":"DM",
"iso_name":"DOMINICA",
"name":"_DOMINICA".loc(),
"region":"xx"},
{"iso_code":"DO",
"iso_name":"DOMINICAN REPUBLIC",
"name":"_DOMINICAN_REPUBLIC".loc(),
"region":"xx"},
{"iso_code":"EC",
"iso_name":"ECUADOR",
"name":"_ECUADOR".loc(),
"region":"xx"},
{"iso_code":"EG",
"iso_name":"EGYPT",
"name":"_EGYPT".loc(),
"region":"xx"},
{"iso_code":"SV",
"iso_name":"EL SALVADOR",
"name":"_EL_SALVADOR".loc(),
"region":"xx"},
{"iso_code":"GQ",
"iso_name":"EQUATORIAL GUINEA",
"name":"_EQUATORIAL_GUINEA".loc(),
"region":"xx"},
{"iso_code":"ER",
"iso_name":"ERITREA",
"name":"_ERITREA".loc(),
"region":"xx"},
{"iso_code":"EE",
"iso_name":"ESTONIA",
"name":"_ESTONIA".loc(),
"region":"xx"},
{"iso_code":"ET",
"iso_name":"ETHIOPIA",
"name":"_ETHIOPIA".loc(),
"region":"xx"},
{"iso_code":"FK",
"iso_name":"FALKLAND ISLANDS (MALVINAS)",
"name":"_FALKLAND_ISLANDS (MALVINAS)".loc(),
"region":"xx"},
{"iso_code":"FO",
"iso_name":"FAROE ISLANDS",
"name":"_FAROE_ISLANDS".loc(),
"region":"xx"},
{"iso_code":"FJ",
"iso_name":"FIJI",
"name":"_FIJI".loc(),
"region":"xx"},
{"iso_code":"FI",
"iso_name":"FINLAND",
"name":"_FINLAND".loc(),
"region":"xx"},
{"iso_code":"FR",
"iso_name":"FRANCE",
"name":"_FRANCE".loc(),
"region":"xx"},
{"iso_code":"GF",
"iso_name":"FRENCH GUIANA",
"name":"_FRENCH_GUIANA".loc(),
"region":"xx"},
{"iso_code":"PF",
"iso_name":"FRENCH POLYNESIA",
"name":"_FRENCH_POLYNESIA".loc(),
"region":"xx"},
{"iso_code":"TF",
"iso_name":"FRENCH SOUTHERN TERRITORIES",
"name":"_FRENCH_SOUTHERN TERRITORIES".loc(),
"region":"xx"},
{"iso_code":"GA",
"iso_name":"GABON",
"name":"_GABON".loc(),
"region":"xx"},
{"iso_code":"GM",
"iso_name":"GAMBIA",
"name":"_GAMBIA".loc(),
"region":"xx"},
{"iso_code":"GE",
"iso_name":"GEORGIA",
"name":"_GEORGIA".loc(),
"region":"xx"},
{"iso_code":"DE",
"iso_name":"GERMANY",
"name":"_GERMANY".loc(),
"region":"xx"},
{"iso_code":"GH",
"iso_name":"GHANA",
"name":"_GHANA".loc(),
"region":"xx"},
{"iso_code":"GI",
"iso_name":"GIBRALTAR",
"name":"_GIBRALTAR".loc(),
"region":"xx"},
{"iso_code":"GR",
"iso_name":"GREECE",
"name":"_GREECE".loc(),
"region":"xx"},
{"iso_code":"GL",
"iso_name":"GREENLAND",
"name":"_GREENLAND".loc(),
"region":"xx"},
{"iso_code":"GD",
"iso_name":"GRENADA",
"name":"_GRENADA".loc(),
"region":"xx"},
{"iso_code":"GP",
"iso_name":"GUADELOUPE",
"name":"_GUADELOUPE".loc(),
"region":"xx"},
{"iso_code":"GU",
"iso_name":"GUAM",
"name":"_GUAM".loc(),
"region":"xx"},
{"iso_code":"GT",
"iso_name":"GUATEMALA",
"name":"_GUATEMALA".loc(),
"region":"xx"},
{"iso_code":"GG",
"iso_name":"GUERNSEY",
"name":"_GUERNSEY".loc(),
"region":"xx"},
{"iso_code":"GN",
"iso_name":"GUINEA",
"name":"_GUINEA".loc(),
"region":"xx"},
{"iso_code":"GW",
"iso_name":"GUINEA-BISSAU",
"name":"_GUINEA-BISSAU".loc(),
"region":"xx"},
{"iso_code":"GY",
"iso_name":"GUYANA",
"name":"_GUYANA".loc(),
"region":"xx"},
{"iso_code":"HT",
"iso_name":"HAITI",
"name":"_HAITI".loc(),
"region":"xx"},
{"iso_code":"HM",
"iso_name":"HEARD ISLAND AND MCDONALD ISLANDS",
"name":"_HEARD_ISLAND AND MCDONALD ISLANDS".loc(),
"region":"xx"},
{"iso_code":"VA",
"iso_name":"HOLY SEE (VATICAN CITY STATE)",
"name":"_HOLY_SEE (VATICAN CITY STATE)".loc(),
"region":"xx"},
{"iso_code":"HN",
"iso_name":"HONDURAS",
"name":"_HONDURAS".loc(),
"region":"xx"},
{"iso_code":"HK",
"iso_name":"HONG KONG",
"name":"_HONG_KONG".loc(),
"region":"xx"},
{"iso_code":"HU",
"iso_name":"HUNGARY",
"name":"_HUNGARY".loc(),
"region":"xx"},
{"iso_code":"IS",
"iso_name":"ICELAND",
"name":"_ICELAND".loc(),
"region":"xx"},
{"iso_code":"IN",
"iso_name":"INDIA",
"name":"_INDIA".loc(),
"region":"xx"},
{"iso_code":"ID",
"iso_name":"INDONESIA",
"name":"_INDONESIA".loc(),
"region":"xx"},
{"iso_code":"IR",
"iso_name":"IRAN, ISLAMIC REPUBLIC OF",
"name":"_IRAN,_ISLAMIC REPUBLIC OF".loc(),
"region":"xx"},
{"iso_code":"IQ",
"iso_name":"IRAQ",
"name":"_IRAQ".loc(),
"region":"xx"},
{"iso_code":"IE",
"iso_name":"IRELAND",
"name":"_IRELAND".loc(),
"region":"xx"},
{"iso_code":"IM",
"iso_name":"ISLE OF MAN",
"name":"_ISLE_OF MAN".loc(),
"region":"xx"},
{"iso_code":"IL",
"iso_name":"ISRAEL",
"name":"_ISRAEL".loc(),
"region":"xx"},
{"iso_code":"IT",
"iso_name":"ITALY",
"name":"_ITALY".loc(),
"region":"xx"},
{"iso_code":"JM",
"iso_name":"JAMAICA",
"name":"_JAMAICA".loc(),
"region":"xx"},
{"iso_code":"JP",
"iso_name":"JAPAN",
"name":"_JAPAN".loc(),
"region":"xx"},
{"iso_code":"JE",
"iso_name":"JERSEY",
"name":"_JERSEY".loc(),
"region":"xx"},
{"iso_code":"JO",
"iso_name":"JORDAN",
"name":"_JORDAN".loc(),
"region":"xx"},
{"iso_code":"KZ",
"iso_name":"KAZAKHSTAN",
"name":"_KAZAKHSTAN".loc(),
"region":"xx"},
{"iso_code":"KE",
"iso_name":"KENYA",
"name":"_KENYA".loc(),
"region":"xx"},
{"iso_code":"KI",
"iso_name":"KIRIBATI",
"name":"_KIRIBATI".loc(),
"region":"xx"},
{"iso_code":"KP",
"iso_name":"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
"name":"_KOREA,_DEMOCRATIC PEOPLE'S REPUBLIC OF".loc(),
"region":"xx"},
{"iso_code":"KR",
"iso_name":"KOREA, REPUBLIC OF",
"name":"_KOREA,_REPUBLIC OF".loc(),
"region":"xx"},
{"iso_code":"KW",
"iso_name":"KUWAIT",
"name":"_KUWAIT".loc(),
"region":"xx"},
{"iso_code":"KG",
"iso_name":"KYRGYZSTAN",
"name":"_KYRGYZSTAN".loc(),
"region":"xx"},
{"iso_code":"LA",
"iso_name":"LAO PEOPLE'S DEMOCRATIC REPUBLIC",
"name":"_LAO_PEOPLE'S DEMOCRATIC REPUBLIC".loc(),
"region":"xx"},
{"iso_code":"LV",
"iso_name":"LATVIA",
"name":"_LATVIA".loc(),
"region":"xx"},
{"iso_code":"LB",
"iso_name":"LEBANON",
"name":"_LEBANON".loc(),
"region":"xx"},
{"iso_code":"LS",
"iso_name":"LESOTHO",
"name":"_LESOTHO".loc(),
"region":"xx"},
{"iso_code":"LR",
"iso_name":"LIBERIA",
"name":"_LIBERIA".loc(),
"region":"xx"},
{"iso_code":"LY",
"iso_name":"LIBYAN ARAB JAMAHIRIYA",
"name":"_LIBYAN_ARAB JAMAHIRIYA".loc(),
"region":"xx"},
{"iso_code":"LI",
"iso_name":"LIECHTENSTEIN",
"name":"_LIECHTENSTEIN".loc(),
"region":"xx"},
{"iso_code":"LT",
"iso_name":"LITHUANIA",
"name":"_LITHUANIA".loc(),
"region":"xx"},
{"iso_code":"LU",
"iso_name":"LUXEMBOURG",
"name":"_LUXEMBOURG".loc(),
"region":"xx"},
{"iso_code":"MO",
"iso_name":"MACAO",
"name":"_MACAO".loc(),
"region":"xx"},
{"iso_code":"MK",
"iso_name":"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
"name":"_MACEDONIA,_THE FORMER YUGOSLAV REPUBLIC OF".loc(),
"region":"xx"},
{"iso_code":"MG",
"iso_name":"MADAGASCAR",
"name":"_MADAGASCAR".loc(),
"region":"xx"},
{"iso_code":"MW",
"iso_name":"MALAWI",
"name":"_MALAWI".loc(),
"region":"xx"},
{"iso_code":"MY",
"iso_name":"MALAYSIA",
"name":"_MALAYSIA".loc(),
"region":"xx"},
{"iso_code":"MV",
"iso_name":"MALDIVES",
"name":"_MALDIVES".loc(),
"region":"xx"},
{"iso_code":"ML",
"iso_name":"MALI",
"name":"_MALI".loc(),
"region":"xx"},
{"iso_code":"MT",
"iso_name":"MALTA",
"name":"_MALTA".loc(),
"region":"xx"},
{"iso_code":"MH",
"iso_name":"MARSHALL ISLANDS",
"name":"_MARSHALL_ISLANDS".loc(),
"region":"xx"},
{"iso_code":"MQ",
"iso_name":"MARTINIQUE",
"name":"_MARTINIQUE".loc(),
"region":"xx"},
{"iso_code":"MR",
"iso_name":"MAURITANIA",
"name":"_MAURITANIA".loc(),
"region":"xx"},
{"iso_code":"MU",
"iso_name":"MAURITIUS",
"name":"_MAURITIUS".loc(),
"region":"xx"},
{"iso_code":"YT",
"iso_name":"MAYOTTE",
"name":"_MAYOTTE".loc(),
"region":"xx"},
{"iso_code":"MX",
"iso_name":"MEXICO",
"name":"_MEXICO".loc(),
"region":"xx"},
{"iso_code":"FM",
"iso_name":"MICRONESIA, FEDERATED STATES OF",
"name":"_MICRONESIA,_FEDERATED STATES OF".loc(),
"region":"xx"},
{"iso_code":"MD",
"iso_name":"MOLDOVA, REPUBLIC OF",
"name":"_MOLDOVA,_REPUBLIC OF".loc(),
"region":"xx"},
{"iso_code":"MC",
"iso_name":"MONACO",
"name":"_MONACO".loc(),
"region":"xx"},
{"iso_code":"MN",
"iso_name":"MONGOLIA",
"name":"_MONGOLIA".loc(),
"region":"xx"},
{"iso_code":"ME",
"iso_name":"MONTENEGRO",
"name":"_MONTENEGRO".loc(),
"region":"xx"},
{"iso_code":"MS",
"iso_name":"MONTSERRAT",
"name":"_MONTSERRAT".loc(),
"region":"xx"},
{"iso_code":"MA",
"iso_name":"MOROCCO",
"name":"_MOROCCO".loc(),
"region":"xx"},
{"iso_code":"MZ",
"iso_name":"MOZAMBIQUE",
"name":"_MOZAMBIQUE".loc(),
"region":"xx"},
{"iso_code":"MM",
"iso_name":"MYANMAR",
"name":"_MYANMAR".loc(),
"region":"xx"},
{"iso_code":"NA",
"iso_name":"NAMIBIA",
"name":"_NAMIBIA".loc(),
"region":"xx"},
{"iso_code":"NR",
"iso_name":"NAURU",
"name":"_NAURU".loc(),
"region":"xx"},
{"iso_code":"NP",
"iso_name":"NEPAL",
"name":"_NEPAL".loc(),
"region":"xx"},
{"iso_code":"NL",
"iso_name":"NETHERLANDS",
"name":"_NETHERLANDS".loc(),
"region":"xx"},
{"iso_code":"AN",
"iso_name":"NETHERLANDS ANTILLES",
"name":"_NETHERLANDS_ANTILLES".loc(),
"region":"xx"},
{"iso_code":"NC",
"iso_name":"NEW CALEDONIA",
"name":"_NEW_CALEDONIA".loc(),
"region":"xx"},
{"iso_code":"NZ",
"iso_name":"NEW ZEALAND",
"name":"_NEW_ZEALAND".loc(),
"region":"xx"},
{"iso_code":"NI",
"iso_name":"NICARAGUA",
"name":"_NICARAGUA".loc(),
"region":"xx"},
{"iso_code":"NE",
"iso_name":"NIGER",
"name":"_NIGER".loc(),
"region":"xx"},
{"iso_code":"NG",
"iso_name":"NIGERIA",
"name":"_NIGERIA".loc(),
"region":"xx"},
{"iso_code":"NU",
"iso_name":"NIUE",
"name":"_NIUE".loc(),
"region":"xx"},
{"iso_code":"NF",
"iso_name":"NORFOLK ISLAND",
"name":"_NORFOLK_ISLAND".loc(),
"region":"xx"},
{"iso_code":"MP",
"iso_name":"NORTHERN MARIANA ISLANDS",
"name":"_NORTHERN_MARIANA ISLANDS".loc(),
"region":"xx"},
{"iso_code":"NO",
"iso_name":"NORWAY",
"name":"_NORWAY".loc(),
"region":"xx"},
{"iso_code":"OM",
"iso_name":"OMAN",
"name":"_OMAN".loc(),
"region":"xx"},
{"iso_code":"PK",
"iso_name":"PAKISTAN",
"name":"_PAKISTAN".loc(),
"region":"xx"},
{"iso_code":"PW",
"iso_name":"PALAU",
"name":"_PALAU".loc(),
"region":"xx"},
{"iso_code":"PS",
"iso_name":"PALESTINIAN TERRITORY, OCCUPIED",
"name":"_PALESTINIAN_TERRITORY, OCCUPIED".loc(),
"region":"xx"},
{"iso_code":"PA",
"iso_name":"PANAMA",
"name":"_PANAMA".loc(),
"region":"xx"},
{"iso_code":"PG",
"iso_name":"PAPUA NEW GUINEA",
"name":"_PAPUA_NEW GUINEA".loc(),
"region":"xx"},
{"iso_code":"PY",
"iso_name":"PARAGUAY",
"name":"_PARAGUAY".loc(),
"region":"xx"},
{"iso_code":"PE",
"iso_name":"PERU",
"name":"_PERU".loc(),
"region":"xx"},
{"iso_code":"PH",
"iso_name":"PHILIPPINES",
"name":"_PHILIPPINES".loc(),
"region":"xx"},
{"iso_code":"PN",
"iso_name":"PITCAIRN",
"name":"_PITCAIRN".loc(),
"region":"xx"},
{"iso_code":"PL",
"iso_name":"POLAND",
"name":"_POLAND".loc(),
"region":"xx"},
{"iso_code":"PT",
"iso_name":"PORTUGAL",
"name":"_PORTUGAL".loc(),
"region":"xx"},
{"iso_code":"PR",
"iso_name":"PUERTO RICO",
"name":"_PUERTO_RICO".loc(),
"region":"xx"},
{"iso_code":"QA",
"iso_name":"QATAR",
"name":"_QATAR".loc(),
"region":"xx"},
{"iso_code":"RE",
"iso_name":"RÉUNION",
"name":"_RÉUNION".loc(),
"region":"xx"},
{"iso_code":"RO",
"iso_name":"ROMANIA",
"name":"_ROMANIA".loc(),
"region":"xx"},
{"iso_code":"RU",
"iso_name":"RUSSIAN FEDERATION",
"name":"_RUSSIAN_FEDERATION".loc(),
"region":"xx"},
{"iso_code":"RW",
"iso_name":"RWANDA",
"name":"_RWANDA".loc(),
"region":"xx"},
{"iso_code":"BL",
"iso_name":"SAINT BARTHÉLEMY",
"name":"_SAINT_BARTHÉLEMY".loc(),
"region":"xx"},
{"iso_code":"SH",
"iso_name":"SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
"name":"_SAINT_HELENA, ASCENSION AND TRISTAN DA CUNHA".loc(),
"region":"xx"},
{"iso_code":"KN",
"iso_name":"TTS AND NEVIS",
"name":"_TTS_AND NEVIS".loc(),
"region":"xx"},
{"iso_code":"LC",
"iso_name":"SAINT LUCIA",
"name":"_SAINT_LUCIA".loc(),
"region":"xx"},
{"iso_code":"MF",
"iso_name":"SAINT MARTIN",
"name":"_SAINT_MARTIN".loc(),
"region":"xx"},
{"iso_code":"PM",
"iso_name":"SAINT PIERRE AND MIQUELON",
"name":"_SAINT_PIERRE AND MIQUELON".loc(),
"region":"xx"},
{"iso_code":"VC",
"iso_name":"SAINT VINCENT AND THE GRENADINES",
"name":"_SAINT_VINCENT AND THE GRENADINES".loc(),
"region":"xx"},
{"iso_code":"WS",
"iso_name":"SAMOA",
"name":"_SAMOA".loc(),
"region":"xx"},
{"iso_code":"SM",
"iso_name":"SAN MARINO",
"name":"_SAN_MARINO".loc(),
"region":"xx"},
{"iso_code":"ST",
"iso_name":"SAO TOME AND PRINCIPE",
"name":"_SAO_TOME AND PRINCIPE".loc(),
"region":"xx"},
{"iso_code":"SA",
"iso_name":"SAUDI ARABIA",
"name":"_SAUDI_ARABIA".loc(),
"region":"xx"},
{"iso_code":"SN",
"iso_name":"SENEGAL",
"name":"_SENEGAL".loc(),
"region":"xx"},
{"iso_code":"RS",
"iso_name":"SERBIA",
"name":"_SERBIA".loc(),
"region":"xx"},
{"iso_code":"SC",
"iso_name":"SEYCHELLES",
"name":"_SEYCHELLES".loc(),
"region":"xx"},
{"iso_code":"SL",
"iso_name":"SIERRA LEONE",
"name":"_SIERRA_LEONE".loc(),
"region":"xx"},
{"iso_code":"SG",
"iso_name":"SINGAPORE",
"name":"_SINGAPORE".loc(),
"region":"xx"},
{"iso_code":"SK",
"iso_name":"SLOVAKIA",
"name":"_SLOVAKIA".loc(),
"region":"xx"},
{"iso_code":"SI",
"iso_name":"SLOVENIA",
"name":"_SLOVENIA".loc(),
"region":"xx"},
{"iso_code":"SB",
"iso_name":"SOLOMON ISLANDS",
"name":"_SOLOMON_ISLANDS".loc(),
"region":"xx"},
{"iso_code":"SO",
"iso_name":"SOMALIA",
"name":"_SOMALIA".loc(),
"region":"xx"},
{"iso_code":"ZA",
"iso_name":"SOUTH AFRICA",
"name":"_SOUTH_AFRICA".loc(),
"region":"xx"},
{"iso_code":"GS",
"iso_name":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
"name":"_SOUTH_GEORGIA AND THE SOUTH SANDWICH ISLANDS".loc(),
"region":"xx"},
{"iso_code":"ES",
"iso_name":"SPAIN",
"name":"_SPAIN".loc(),
"region":"xx"},
{"iso_code":"LK",
"iso_name":"SRI LANKA",
"name":"_SRI_LANKA".loc(),
"region":"xx"},
{"iso_code":"SD",
"iso_name":"SUDAN",
"name":"_SUDAN".loc(),
"region":"xx"},
{"iso_code":"SR",
"iso_name":"SURINAME",
"name":"_SURINAME".loc(),
"region":"xx"},
{"iso_code":"SJ",
"iso_name":"SVALBARD AND JAN MAYEN",
"name":"_SVALBARD_AND_JAN_MAYEN".loc(),
"region":"xx"},
{"iso_code":"SZ",
"iso_name":"SWAZILAND",
"name":"_SWAZILAND".loc(),
"region":"xx"},
{"iso_code":"SE",
"iso_name":"SWEDEN",
"name":"_SWEDEN".loc(),
"region":"xx"},
{"iso_code":"CH",
"iso_name":"SWITZERLAND",
"name":"_SWITZERLAND".loc(),
"region":"xx"},
{"iso_code":"SY",
"iso_name":"SYRIAN ARAB REPUBLIC",
"name":"_SYRIAN_ARAB_REPUBLIC".loc(),
"region":"xx"},
{"iso_code":"TW",
"iso_name":"TAIWAN, PROVINCE OF CHINA",
"name":"_TAIWAN,_PROVINCE_OF_CHINA".loc(),
"region":"xx"},
{"iso_code":"TJ",
"iso_name":"TAJIKISTAN",
"name":"_TAJIKISTAN".loc(),
"region":"xx"},
{"iso_code":"TZ",
"iso_name":"TANZANIA, UNITED REPUBLIC OF",
"name":"_TANZANIA,_UNITED_REPUBLIC_OF".loc(),
"region":"xx"},
{"iso_code":"TH",
"iso_name":"THAILAND",
"name":"_THAILAND".loc(),
"region":"xx"},
{"iso_code":"TL",
"iso_name":"TIMOR-LESTE",
"name":"_TIMOR-LESTE".loc(),
"region":"xx"},
{"iso_code":"TG",
"iso_name":"TOGO",
"name":"_TOGO".loc(),
"region":"xx"},
{"iso_code":"TK",
"iso_name":"TOKELAU",
"name":"_TOKELAU".loc(),
"region":"xx"},
{"iso_code":"TO",
"iso_name":"TONGA",
"name":"_TONGA".loc(),
"region":"xx"},
{"iso_code":"TT",
"iso_name":"TRINIDAD AND TOBAGO",
"name":"_TRINIDAD_AND_TOBAGO".loc(),
"region":"xx"},
{"iso_code":"TN",
"iso_name":"TUNISIA",
"name":"_TUNISIA".loc(),
"region":"xx"},
{"iso_code":"TR",
"iso_name":"TURKEY",
"name":"_TURKEY".loc(),
"region":"xx"},
{"iso_code":"TM",
"iso_name":"TURKMENISTAN",
"name":"_TURKMENISTAN".loc(),
"region":"xx"},
{"iso_code":"TC",
"iso_name":"TURKS AND CAICOS ISLANDS",
"name":"_TURKS_AND_CAICOS_ISLANDS".loc(),
"region":"xx"},
{"iso_code":"TV",
"iso_name":"TUVALU",
"name":"_TUVALU".loc(),
"region":"xx"},
{"iso_code":"UG",
"iso_name":"UGANDA",
"name":"_UGANDA".loc(),
"region":"xx"},
{"iso_code":"UA",
"iso_name":"UKRAINE",
"name":"_UKRAINE".loc(),
"region":"xx"},
{"iso_code":"AE",
"iso_name":"UNITED ARAB EMIRATES",
"name":"_UNITED_ARAB_EMIRATES".loc(),
"region":"xx"},
{"iso_code":"GB",
"iso_name":"UNITED KINGDOM",
"name":"_UNITED_KINGDOM".loc(),
"region":"xx"},
{"iso_code":"US",
"iso_name":"UNITED STATES",
"name":"_UNITED_STATES".loc(),
"region":"xx"},
{"iso_code":"UM",
"iso_name":"UNITED STATES MINOR OUTLYING ISLANDS",
"name":"_UNITED_STATES_MINOR_OUTLYING_ISLANDS".loc(),
"region":"xx"},
{"iso_code":"UY",
"iso_name":"URUGUAY",
"name":"_URUGUAY".loc(),
"region":"xx"},
{"iso_code":"UZ",
"iso_name":"UZBEKISTAN",
"name":"_UZBEKISTAN".loc(),
"region":"xx"},
{"iso_code":"VU",
"iso_name":"VANUATU",
"name":"_VANUATU".loc(),
"region":"xx"},
{"iso_code":"see HOLY SEE",
"iso_name":"VATICAN CITY STATE",
"name":"_VATICAN_CITY_STATE".loc(),
"region":"xx"},
{"iso_code":"VE",
"iso_name":"VENEZUELA, BOLIVARIAN REPUBLIC OF",
"name":"_VENEZUELA,_BOLIVARIAN_REPUBLIC_OF".loc(),
"region":"xx"},
{"iso_code":"VN",
"iso_name":"VIET NAM",
"name":"_VIET_NAM".loc(),
"region":"xx"},
{"iso_code":"VG",
"iso_name":"VIRGIN ISLANDS, BRITISH",
"name":"_VIRGIN_ISLANDS, BRITISH".loc(),
"region":"xx"},
{"iso_code":"VI",
"iso_name":"VIRGIN ISLANDS, U.S.",
"name":"_VIRGIN_ISLANDS,_U.S.".loc(),
"region":"xx"},
{"iso_code":"WF",
"iso_name":"WALLIS AND FUTUNA",
"name":"_WALLIS_AND_FUTUNA".loc(),
"region":"xx"},
{"iso_code":"EH",
"iso_name":"WESTERN SAHARA",
"name":"_WESTERN_SAHARA".loc(),
"region":"xx"},
{"iso_code":"YE",
"iso_name":"YEMEN",
"name":"_YEMEN".loc(),
"region":"xx"},
{"iso_code":"ZM",
"iso_name":"ZAMBIA",
"name":"_ZAMBIA".loc(),
"region":"xx"},
{"iso_code":"ZW",
"iso_name":"ZIMBABWE",
"name":"_ZIMBABWE".loc(),
"region":"xx"},
{"iso_code":"_S",
"iso_name":"SOUTHERN SUDAN TERRITORY, PROVISIONAL",
"name":"_SOUTHERN_SUDAN_TERRITORY,_PROVISIONAL".loc(),
"region":"xx"}
];
