// ==========================================================================
// Project:   Klb
// Copyright: ©2009 Kiva Microfunds
// Licensed under MIT License Terms (see license.js)
// ==========================================================================
/*globals Klb */

Klb.COUNTRIES_ISO = [

{"iso_code":"AF",
"name":"AFGHANISTAN",
"region":"xx"},
{"iso_code":"AX",
"name":"ÅLAND ISLANDS",
"region":"xx"},
{"iso_code":"AL",
"name":"ALBANIA",
"region":"xx"},
{"iso_code":"DZ",
"name":"ALGERIA",
"region":"xx"},
{"iso_code":"AS",
"name":"AMERICAN SAMOA",
"region":"xx"},
{"iso_code":"AD",
"name":"ANDORRA",
"region":"xx"},
{"iso_code":"AO",
"name":"ANGOLA",
"region":"xx"},
{"iso_code":"AI",
"name":"ANGUILLA",
"region":"xx"},
{"iso_code":"AQ",
"name":"ANTARCTICA",
"region":"xx"},
{"iso_code":"AG",
"name":"ANTIGUA AND BARBUDA",
"region":"xx"},
{"iso_code":"AR",
"name":"ARGENTINA",
"region":"xx"},
{"iso_code":"AM",
"name":"ARMENIA",
"region":"xx"},
{"iso_code":"AW",
"name":"ARUBA",
"region":"xx"},
{"iso_code":"AU",
"name":"AUSTRALIA",
"region":"xx"},
{"iso_code":"AT",
"name":"AUSTRIA",
"region":"xx"},
{"iso_code":"AZ",
"name":"_AZERBAIJAN".loc(),
"region":"xx"},
{"iso_code":"BS",
"name":"BAHAMAS",
"region":"xx"},
{"iso_code":"BH",
"name":"BAHRAIN",
"region":"xx"},
{"iso_code":"BD",
"name":"BANGLADESH",
"region":"xx"},
{"iso_code":"BB",
"name":"BARBADOS",
"region":"xx"},
{"iso_code":"BY",
"name":"BELARUS",
"region":"xx"},
{"iso_code":"BE",
"name":"BELGIUM",
"region":"xx"},
{"iso_code":"BZ",
"name":"BELIZE",
"region":"xx"},
{"iso_code":"BJ",
"name":"BENIN",
"region":"xx"},
{"iso_code":"BM",
"name":"BERMUDA",
"region":"xx"},
{"iso_code":"BT",
"name":"BHUTAN",
"region":"xx"},
{"iso_code":"BO",
"name":"BOLIVIA, PLURINATIONAL STATE OF",
"region":"xx"},
{"iso_code":"BA",
"name":"BOSNIA AND HERZEGOVINA",
"region":"xx"},
{"iso_code":"BW",
"name":"BOTSWANA",
"region":"xx"},
{"iso_code":"BV",
"name":"BOUVET ISLAND",
"region":"xx"},
{"iso_code":"BR",
"name":"BRAZIL",
"region":"xx"},
{"iso_code":"IO",
"name":"BRITISH INDIAN OCEAN TERRITORY",
"region":"xx"},
{"iso_code":"BN",
"name":"BRUNEI DARUSSALAM",
"region":"xx"},
{"iso_code":"BG",
"name":"BULGARIA",
"region":"xx"},
{"iso_code":"BF",
"name":"BURKINA FASO",
"region":"xx"},
{"iso_code":"BI",
"name":"BURUNDI",
"region":"xx"},
{"iso_code":"KH",
"name":"_CAMBODIA".loc(),
"region":"xx"},
{"iso_code":"CM",
"name":"CAMEROON",
"region":"xx"},
{"iso_code":"CA",
"name":"CANADA",
"region":"xx"},
{"iso_code":"CV",
"name":"CAPE VERDE",
"region":"xx"},
{"iso_code":"KY",
"name":"CAYMAN ISLANDS",
"region":"xx"},
{"iso_code":"CF",
"name":"CENTRAL AFRICAN REPUBLIC",
"region":"xx"},
{"iso_code":"TD",
"name":"CHAD",
"region":"xx"},
{"iso_code":"CL",
"name":"CHILE",
"region":"xx"},
{"iso_code":"CN",
"name":"CHINA",
"region":"xx"},
{"iso_code":"CX",
"name":"CHRISTMAS ISLAND",
"region":"xx"},
{"iso_code":"CC",
"name":"COCOS (KEELING) ISLANDS",
"region":"xx"},
{"iso_code":"CO",
"name":"COLOMBIA",
"region":"xx"},
{"iso_code":"KM",
"name":"COMOROS",
"region":"xx"},
{"iso_code":"CG",
"name":"CONGO",
"region":"xx"},
{"iso_code":"CD",
"name":"CONGO, THE DEMOCRATIC REPUBLIC OF THE",
"region":"xx"},
{"iso_code":"CK",
"name":"COOK ISLANDS",
"region":"xx"},
{"iso_code":"CR",
"name":"COSTA RICA",
"region":"xx"},
{"iso_code":"CI",
"name":"CÔTE D'IVOIRE",
"region":"xx"},
{"iso_code":"HR",
"name":"CROATIA",
"region":"xx"},
{"iso_code":"CU",
"name":"CUBA",
"region":"xx"},
{"iso_code":"CY",
"name":"CYPRUS",
"region":"xx"},
{"iso_code":"CZ",
"name":"CZECH REPUBLIC",
"region":"xx"},
{"iso_code":"DK",
"name":"DENMARK",
"region":"xx"},
{"iso_code":"DJ",
"name":"DJIBOUTI",
"region":"xx"},
{"iso_code":"DM",
"name":"DOMINICA",
"region":"xx"},
{"iso_code":"DO",
"name":"DOMINICAN REPUBLIC",
"region":"xx"},
{"iso_code":"EC",
"name":"ECUADOR",
"region":"xx"},
{"iso_code":"EG",
"name":"EGYPT",
"region":"xx"},
{"iso_code":"SV",
"name":"EL SALVADOR",
"region":"xx"},
{"iso_code":"GQ",
"name":"EQUATORIAL GUINEA",
"region":"xx"},
{"iso_code":"ER",
"name":"ERITREA",
"region":"xx"},
{"iso_code":"EE",
"name":"ESTONIA",
"region":"xx"},
{"iso_code":"ET",
"name":"ETHIOPIA",
"region":"xx"},
{"iso_code":"FK",
"name":"FALKLAND ISLANDS (MALVINAS)",
"region":"xx"},
{"iso_code":"FO",
"name":"FAROE ISLANDS",
"region":"xx"},
{"iso_code":"FJ",
"name":"FIJI",
"region":"xx"},
{"iso_code":"FI",
"name":"FINLAND",
"region":"xx"},
{"iso_code":"FR",
"name":"FRANCE",
"region":"xx"},
{"iso_code":"GF",
"name":"FRENCH GUIANA",
"region":"xx"},
{"iso_code":"PF",
"name":"FRENCH POLYNESIA",
"region":"xx"},
{"iso_code":"TF",
"name":"FRENCH SOUTHERN TERRITORIES",
"region":"xx"},
{"iso_code":"GA",
"name":"GABON",
"region":"xx"},
{"iso_code":"GM",
"name":"GAMBIA",
"region":"xx"},
{"iso_code":"GE",
"name":"GEORGIA",
"region":"xx"},
{"iso_code":"DE",
"name":"GERMANY",
"region":"xx"},
{"iso_code":"GH",
"name":"GHANA",
"region":"xx"},
{"iso_code":"GI",
"name":"GIBRALTAR",
"region":"xx"},
{"iso_code":"GR",
"name":"GREECE",
"region":"xx"},
{"iso_code":"GL",
"name":"GREENLAND",
"region":"xx"},
{"iso_code":"GD",
"name":"GRENADA",
"region":"xx"},
{"iso_code":"GP",
"name":"GUADELOUPE",
"region":"xx"},
{"iso_code":"GU",
"name":"GUAM",
"region":"xx"},
{"iso_code":"GT",
"name":"GUATEMALA",
"region":"xx"},
{"iso_code":"GG",
"name":"GUERNSEY",
"region":"xx"},
{"iso_code":"GN",
"name":"GUINEA",
"region":"xx"},
{"iso_code":"GW",
"name":"GUINEA-BISSAU",
"region":"xx"},
{"iso_code":"GY",
"name":"GUYANA",
"region":"xx"},
{"iso_code":"HT",
"name":"HAITI",
"region":"xx"},
{"iso_code":"HM",
"name":"HEARD ISLAND AND MCDONALD ISLANDS",
"region":"xx"},
{"iso_code":"VA",
"name":"HOLY SEE (VATICAN CITY STATE)",
"region":"xx"},
{"iso_code":"HN",
"name":"HONDURAS",
"region":"xx"},
{"iso_code":"HK",
"name":"HONG KONG",
"region":"xx"},
{"iso_code":"HU",
"name":"HUNGARY",
"region":"xx"},
{"iso_code":"IS",
"name":"ICELAND",
"region":"xx"},
{"iso_code":"IN",
"name":"INDIA",
"region":"xx"},
{"iso_code":"ID",
"name":"INDONESIA",
"region":"xx"},
{"iso_code":"IR",
"name":"IRAN, ISLAMIC REPUBLIC OF",
"region":"xx"},
{"iso_code":"IQ",
"name":"IRAQ",
"region":"xx"},
{"iso_code":"IE",
"name":"IRELAND",
"region":"xx"},
{"iso_code":"IM",
"name":"ISLE OF MAN",
"region":"xx"},
{"iso_code":"IL",
"name":"ISRAEL",
"region":"xx"},
{"iso_code":"IT",
"name":"ITALY",
"region":"xx"},
{"iso_code":"JM",
"name":"JAMAICA",
"region":"xx"},
{"iso_code":"JP",
"name":"JAPAN",
"region":"xx"},
{"iso_code":"JE",
"name":"JERSEY",
"region":"xx"},
{"iso_code":"JO",
"name":"JORDAN",
"region":"xx"},
{"iso_code":"KZ",
"name":"KAZAKHSTAN",
"region":"xx"},
{"iso_code":"KE",
"name":"KENYA",
"region":"xx"},
{"iso_code":"KI",
"name":"KIRIBATI",
"region":"xx"},
{"iso_code":"KP",
"name":"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
"region":"xx"},
{"iso_code":"KR",
"name":"KOREA, REPUBLIC OF",
"region":"xx"},
{"iso_code":"KW",
"name":"KUWAIT",
"region":"xx"},
{"iso_code":"KG",
"name":"KYRGYZSTAN",
"region":"xx"},
{"iso_code":"LA",
"name":"LAO PEOPLE'S DEMOCRATIC REPUBLIC",
"region":"xx"},
{"iso_code":"LV",
"name":"LATVIA",
"region":"xx"},
{"iso_code":"LB",
"name":"LEBANON",
"region":"xx"},
{"iso_code":"LS",
"name":"LESOTHO",
"region":"xx"},
{"iso_code":"LR",
"name":"LIBERIA",
"region":"xx"},
{"iso_code":"LY",
"name":"LIBYAN ARAB JAMAHIRIYA",
"region":"xx"},
{"iso_code":"LI",
"name":"LIECHTENSTEIN",
"region":"xx"},
{"iso_code":"LT",
"name":"LITHUANIA",
"region":"xx"},
{"iso_code":"LU",
"name":"LUXEMBOURG",
"region":"xx"},
{"iso_code":"MO",
"name":"MACAO",
"region":"xx"},
{"iso_code":"MK",
"name":"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
"region":"xx"},
{"iso_code":"MG",
"name":"MADAGASCAR",
"region":"xx"},
{"iso_code":"MW",
"name":"MALAWI",
"region":"xx"},
{"iso_code":"MY",
"name":"MALAYSIA",
"region":"xx"},
{"iso_code":"MV",
"name":"MALDIVES",
"region":"xx"},
{"iso_code":"ML",
"name":"MALI",
"region":"xx"},
{"iso_code":"MT",
"name":"MALTA",
"region":"xx"},
{"iso_code":"MH",
"name":"MARSHALL ISLANDS",
"region":"xx"},
{"iso_code":"MQ",
"name":"MARTINIQUE",
"region":"xx"},
{"iso_code":"MR",
"name":"MAURITANIA",
"region":"xx"},
{"iso_code":"MU",
"name":"MAURITIUS",
"region":"xx"},
{"iso_code":"YT",
"name":"MAYOTTE",
"region":"xx"},
{"iso_code":"MX",
"name":"MEXICO",
"region":"xx"},
{"iso_code":"FM",
"name":"MICRONESIA, FEDERATED STATES OF",
"region":"xx"},
{"iso_code":"MD",
"name":"MOLDOVA, REPUBLIC OF",
"region":"xx"},
{"iso_code":"MC",
"name":"MONACO",
"region":"xx"},
{"iso_code":"MN",
"name":"MONGOLIA",
"region":"xx"},
{"iso_code":"ME",
"name":"MONTENEGRO",
"region":"xx"},
{"iso_code":"MS",
"name":"MONTSERRAT",
"region":"xx"},
{"iso_code":"MA",
"name":"MOROCCO",
"region":"xx"},
{"iso_code":"MZ",
"name":"MOZAMBIQUE",
"region":"xx"},
{"iso_code":"MM",
"name":"MYANMAR",
"region":"xx"},
{"iso_code":"NA",
"name":"NAMIBIA",
"region":"xx"},
{"iso_code":"NR",
"name":"NAURU",
"region":"xx"},
{"iso_code":"NP",
"name":"NEPAL",
"region":"xx"},
{"iso_code":"NL",
"name":"NETHERLANDS",
"region":"xx"},
{"iso_code":"AN",
"name":"NETHERLANDS ANTILLES",
"region":"xx"},
{"iso_code":"NC",
"name":"NEW CALEDONIA",
"region":"xx"},
{"iso_code":"NZ",
"name":"NEW ZEALAND",
"region":"xx"},
{"iso_code":"NI",
"name":"NICARAGUA",
"region":"xx"},
{"iso_code":"NE",
"name":"NIGER",
"region":"xx"},
{"iso_code":"NG",
"name":"NIGERIA",
"region":"xx"},
{"iso_code":"NU",
"name":"NIUE",
"region":"xx"},
{"iso_code":"NF",
"name":"NORFOLK ISLAND",
"region":"xx"},
{"iso_code":"MP",
"name":"NORTHERN MARIANA ISLANDS",
"region":"xx"},
{"iso_code":"NO",
"name":"NORWAY",
"region":"xx"},
{"iso_code":"OM",
"name":"OMAN",
"region":"xx"},
{"iso_code":"PK",
"name":"PAKISTAN",
"region":"xx"},
{"iso_code":"PW",
"name":"PALAU",
"region":"xx"},
{"iso_code":"PS",
"name":"PALESTINIAN TERRITORY, OCCUPIED",
"region":"xx"},
{"iso_code":"PA",
"name":"PANAMA",
"region":"xx"},
{"iso_code":"PG",
"name":"PAPUA NEW GUINEA",
"region":"xx"},
{"iso_code":"PY",
"name":"PARAGUAY",
"region":"xx"},
{"iso_code":"PE",
"name":"PERU",
"region":"xx"},
{"iso_code":"PH",
"name":"PHILIPPINES",
"region":"xx"},
{"iso_code":"PN",
"name":"PITCAIRN",
"region":"xx"},
{"iso_code":"PL",
"name":"POLAND",
"region":"xx"},
{"iso_code":"PT",
"name":"PORTUGAL",
"region":"xx"},
{"iso_code":"PR",
"name":"PUERTO RICO",
"region":"xx"},
{"iso_code":"QA",
"name":"QATAR",
"region":"xx"},
{"iso_code":"RE",
"name":"RÉUNION",
"region":"xx"},
{"iso_code":"RO",
"name":"ROMANIA",
"region":"xx"},
{"iso_code":"RU",
"name":"RUSSIAN FEDERATION",
"region":"xx"},
{"iso_code":"RW",
"name":"RWANDA",
"region":"xx"},
{"iso_code":"BL",
"name":"SAINT BARTHÉLEMY",
"region":"xx"},
{"iso_code":"SH",
"name":"SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
"region":"xx"},
{"iso_code":"KN",
"name":"TTS AND NEVIS",
"region":"xx"},
{"iso_code":"LC",
"name":"SAINT LUCIA",
"region":"xx"},
{"iso_code":"MF",
"name":"SAINT MARTIN",
"region":"xx"},
{"iso_code":"PM",
"name":"SAINT PIERRE AND MIQUELON",
"region":"xx"},
{"iso_code":"VC",
"name":"SAINT VINCENT AND THE GRENADINES",
"region":"xx"},
{"iso_code":"WS",
"name":"SAMOA",
"region":"xx"},
{"iso_code":"SM",
"name":"SAN MARINO",
"region":"xx"},
{"iso_code":"ST",
"name":"SAO TOME AND PRINCIPE",
"region":"xx"},
{"iso_code":"SA",
"name":"SAUDI ARABIA",
"region":"xx"},
{"iso_code":"SN",
"name":"SENEGAL",
"region":"xx"},
{"iso_code":"RS",
"name":"SERBIA",
"region":"xx"},
{"iso_code":"SC",
"name":"SEYCHELLES",
"region":"xx"},
{"iso_code":"SL",
"name":"SIERRA LEONE",
"region":"xx"},
{"iso_code":"SG",
"name":"SINGAPORE",
"region":"xx"},
{"iso_code":"SK",
"name":"SLOVAKIA",
"region":"xx"},
{"iso_code":"SI",
"name":"SLOVENIA",
"region":"xx"},
{"iso_code":"SB",
"name":"SOLOMON ISLANDS",
"region":"xx"},
{"iso_code":"SO",
"name":"SOMALIA",
"region":"xx"},
{"iso_code":"ZA",
"name":"SOUTH AFRICA",
"region":"xx"},
{"iso_code":"GS",
"name":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
"region":"xx"},
{"iso_code":"_S",
"name":"SOUTHERN SUDAN TERRITORY, PROVISIONAL",
"region":"xx"},
{"iso_code":"ES",
"name":"SPAIN",
"region":"xx"},
{"iso_code":"LK",
"name":"SRI LANKA",
"region":"xx"},
{"iso_code":"SD",
"name":"SUDAN",
"region":"xx"},
{"iso_code":"SR",
"name":"SURINAME",
"region":"xx"},
{"iso_code":"SJ",
"name":"SVALBARD AND JAN MAYEN",
"region":"xx"},
{"iso_code":"SZ",
"name":"SWAZILAND",
"region":"xx"},
{"iso_code":"SE",
"name":"SWEDEN",
"region":"xx"},
{"iso_code":"CH",
"name":"SWITZERLAND",
"region":"xx"},
{"iso_code":"SY",
"name":"SYRIAN ARAB REPUBLIC",
"region":"xx"},
{"iso_code":"TW",
"name":"TAIWAN, PROVINCE OF CHINA",
"region":"xx"},
{"iso_code":"TJ",
"name":"TAJIKISTAN",
"region":"xx"},
{"iso_code":"TZ",
"name":"TANZANIA, UNITED REPUBLIC OF",
"region":"xx"},
{"iso_code":"TH",
"name":"THAILAND",
"region":"xx"},
{"iso_code":"TL",
"name":"TIMOR-LESTE",
"region":"xx"},
{"iso_code":"TG",
"name":"TOGO",
"region":"xx"},
{"iso_code":"TK",
"name":"TOKELAU",
"region":"xx"},
{"iso_code":"TO",
"name":"TONGA",
"region":"xx"},
{"iso_code":"TT",
"name":"TRINIDAD AND TOBAGO",
"region":"xx"},
{"iso_code":"TN",
"name":"TUNISIA",
"region":"xx"},
{"iso_code":"TR",
"name":"TURKEY",
"region":"xx"},
{"iso_code":"TM",
"name":"TURKMENISTAN",
"region":"xx"},
{"iso_code":"TC",
"name":"TURKS AND CAICOS ISLANDS",
"region":"xx"},
{"iso_code":"TV",
"name":"TUVALU",
"region":"xx"},
{"iso_code":"UG",
"name":"UGANDA",
"region":"xx"},
{"iso_code":"UA",
"name":"UKRAINE",
"region":"xx"},
{"iso_code":"AE",
"name":"UNITED ARAB EMIRATES",
"region":"xx"},
{"iso_code":"GB",
"name":"UNITED KINGDOM",
"region":"xx"},
{"iso_code":"US",
"name":"UNITED STATES",
"region":"xx"},
{"iso_code":"UM",
"name":"UNITED STATES MINOR OUTLYING ISLANDS",
"region":"xx"},
{"iso_code":"UY",
"name":"URUGUAY",
"region":"xx"},
{"iso_code":"UZ",
"name":"UZBEKISTAN",
"region":"xx"},
{"iso_code":"VU",
"name":"VANUATU",
"region":"xx"},
{"iso_code":"see HOLY SEE",
"name":"VATICAN CITY STATE",
"region":"xx"},
{"iso_code":"VE",
"name":"VENEZUELA, BOLIVARIAN REPUBLIC OF",
"region":"xx"},
{"iso_code":"VN",
"name":"VIET NAM",
"region":"xx"},
{"iso_code":"VG",
"name":"VIRGIN ISLANDS, BRITISH",
"region":"xx"},
{"iso_code":"VI",
"name":"VIRGIN ISLANDS, U.S.",
"region":"xx"},
{"iso_code":"WF",
"name":"WALLIS AND FUTUNA",
"region":"xx"},
{"iso_code":"EH",
"name":"WESTERN SAHARA",
"region":"xx"},
{"iso_code":"YE",
"name":"YEMEN",
"region":"xx"},
{"iso_code":"ZM",
"name":"ZAMBIA",
"region":"xx"},
{"iso_code":"ZW",
"name":"ZIMBABWE",
"region":"xx"}
];
