// ==========================================================================
// Project:   Klb
// Copyright: ©2009 Kiva Microfunds
// Licensed under MIT License Terms (see license.js)
// ==========================================================================
/*globals Klb */

// Place strings you want to localize here.  In your app, use the key and
// localize it using "key string".loc().  HINT: For your key names, use the
// english string with an underscore in front.  This way you can still see
// how your UI will look and you'll notice right away when something needs a
// localized string added to this file!
//
SC.stringsFor('Français', {
  // "_String Key": "Localized String"
  
  //// General
	"_KlbTitle": "Kiva en Français",
	"_OK": "OK",
	"_Edit": "Modifier",
	
	//// Primary Sections
	"_About": "À Propos",
	"_Choose_A_Loan": "Choisir un Projet",
	"_Learn_More": "En Savoir Plus",
	"_Register": "S'inscrire",
	"_Demo": "Demo",
	
	//// Chrome
	"_Checkout": "Finaliser",
	// sort drop down
  "_Sort_by": "Trier par",
	"_Loan_Amount": "Montant du prêt",
	"_Amount_Remaining": "Restant à financer",
	"_Expiring_Soon": "Date d'expiration",
	"_Most_Recent": "Les plus récents",
	"_List_Grid":"Liste Grille",
	"_List":"Liste",
	/// Sidebar
	"_Filter Options":"Recherche Avancée",
	"_Search": "Recherche",
  "_Countries": "Pays",
  "_Sectors": "Secteurs",
  "_Gender": "Sexe",
  "_Female": "Femme",
  "_Male": "Homme",
  "_Gender": "Sexe",
  "_Sector": "Secteur",
  "_Borrowers": "Emprunteurs",
  "_Partner_Rating": "Note du partenaire",
  "_Groups": "Groupes",
  "_Reset": "Reset",
  "_Save": "Enregistrer",

	// Countries Popup
	"_Choose Countries":"Choisir le pays",

	// Sectors Popup
	"_Choose Sectors":"Choisir un secteur",
	
	//loan_list item"
	"_Loan_Use":"But",
	"_Country": "Pays",
	"_Rating": "Note",
	"_Needed_Out_Of":"besoin total de",
	
	// Countries
	"_AFGHANISTAN":"Afghanistan",
	"_ÅLLAND_ISLANDS":"Ålland Islands",
	"_ALBANIA":"Albanie",
	"_ALGERIA":"Algérie",
	"_AMERICAN_SAMOA":"Samoa",
	"_ANDORRA":"Andorre",
	"_ANGOLA":"Angola",
	"_ANGUILLA":"Anguilla",
	"_ANTARCTICA":"Antarctique",
	"_ANTIGUA_AND BARBUDA":"Antigua And Barbuda",
	"_ARGENTINA":"Argentine",
	"_ARMENIA":"Arménie",
	"_ARUBA":"Aruba",
	"_AUSTRALIA":"Australie",
	"_AUSTRIA":"Autriche",
	"_AZERBAIJAN":"Azerbaïdjan",
	"_BAHAMAS":"Bahamas",
	"_BAHRAIN":"Bahreïn",
	"_BANGLADESH":"Bangladesh",
	"_BARBADOS":"Barbades",
	"_BELARUS":"Biélorussie",
	"_BELGIUM":"Belgique",
	"_BELIZE":"Bélize",
	"_BENIN":"Bénin",
	"_BERMUDA":"Bermudes",
	"_BHUTAN":"Boutan",
	"_BOLIVIA,_PLURINATIONAL STATE OF":"Bolivie",
	"_BOSNIA_AND HERZEGOVINA":"Bosnie et Herzégovine",
	"_BOTSWANA":"Botswana",
	"_BOUVET_ISLAND":"Bouvet Island",
	"_BRAZIL":"Brésil",
	"_BRITISH_INDIAN OCEAN TERRITORY":"British Indian Ocean Territory",
	"_BRUNEI_DARUSSALAM":"Brunéi Darussalam",
	"_BULGARIA":"Bulgarie",
	"_BURKINA_FASO":"Burkina Faso",
	"_BURUNDI":"Burundi",
	"_CAMBODIA":"Cambodge",
	"_CAMEROON":"Cameroun",
	"_CANADA":"Canada",
	"_CAPE_VERDE":"Cape Vert",
	"_CAYMAN_ISLANDS":"Iles Cayman",
	"_CENTRAL_AFRICAN REPUBLIC":"République Centrafricaine",
	"_CHAD":"Chad",
	"_CHILE":"Chilie",
	"_CHINA":"Chine",
	"_CHRISTMAS_ISLAND":"Christmas Island",
	"_COCOS_(KEELING)_ISLANDS":"Cocos Islands",
	"_COLOMBIA":"Colombie",
	"_COMOROS":"Comores",
	"_CONGO":"Congo",
	"_CONGO,_THE DEMOCRATIC REPUBLIC OF THE":"République du Congo",
	"_COOK_ISLANDS":"Iles Cook",
	"_COSTA_RICA":"Costa Rica",
	"_CÔTE_D'IVOIRE":"Côte d'Ivoire",
	"_CROATIA":"Croatie",
	"_CUBA":"Cuba",
	"_CYPRUS":"Chypre",
	"_CZECH_REPUBLIC":"République Tchèque",
	"_DENMARK":"Danemark",
	"_DJIBOUTI":"Djibouti",
	"_DOMINICA":"Dominica",
	"_DOMINICAN_REPUBLIC":"Republique Dominicaine",
	"_ECUADOR":"Equateur",
	"_EGYPT":"Egypte",
	"_EL_SALVADOR":"Salvador",
	"_EQUATORIAL_GUINEA":"Guinée Equatoriale",
	"_ERITREA":"Erythrée",
	"_ESTONIA":"Estonie",
	"_ETHIOPIA":"Ethiopie",
	"_FALKLAND_ISLANDS_(MALVINAS)":"Iles Falkland",
	"_FAROE_ISLANDS":"Iles Féroé",
	"_FIJI":"Fiji",
	"_FINLAND":"Finlande",
	"_FRANCE":"France",
	"_FRENCH_GUIANA":"Guyane Française",
	"_FRENCH_POLYNESIA":"Polynésie Française",
	"_FRENCH_SOUTHERN TERRITORIES":"Territoires Français du Sud",
	"_GABON":"Gabon",
	"_GAMBIA":"Gambie",
	"_GEORGIA":"Géorgie",
	"_GERMANY":"Allemagne",
	"_GHANA":"Ghana",
	"_GIBRALTAR":"Gibraltar",
	"_GREECE":"Grèce",
	"_GREENLAND":"Groënland",
	"_GRENADA":"Grenade",
	"_GUADELOUPE":"Guadeloupe",
	"_GUAM":"Guam",
	"_GUATEMALA":"Guatemala",
	"_GUERNSEY":"Guernsey",
	"_GUINEA":"Guinée",
	"_GUINEA-BISSAU":"Guinée-Bissau",
	"_GUYANA":"Guyane",
	"_HAITI":"Haïti",
	"_HEARD_ISLAND AND MCDONALD ISLANDS":"Ile Heard et Ile Mcdonald",
	"_HONDURAS":"Honduras",
	"_HONG_KONG":"Hong Kong",
	"_HUNGARY":"Hongrie",
	"_ICELAND":"Islande",
	"_INDIA":"Inde",
	"_INDONESIA":"Indonésie",
	"_IRAN,_ISLAMIC REPUBLIC OF":"Iran",
	"_IRAQ":"Irak",
	"_IRELAND":"Irlande",
	"_ISLE_OF MAN":"Ile de Man",
	"_ISRAEL":"Israël",
	"_ITALY":"Italie",
	"_JAMAICA":"Jamaïque",
	"_JAPAN":"Japon",
	"_JERSEY":"Jersey",
	"_JORDAN":"Jordanie",
	"_KAZAKHSTAN":"Kazakhstan",
	"_KENYA":"Kenya",
	"_KIRIBATI":"Kiribati",
	"_KOREA,_DEMOCRATIC PEOPLE'S REPUBLIC OF":"Corée du Sud",
	"_KOREA,_REPUBLIC OF":"Corée du Nord",
	"_KUWAIT":"Koweït",
	"_KYRGYZSTAN":"Kirghizistan",
	"_LAO_PEOPLE'S DEMOCRATIC REPUBLIC":"Laos",
	"_LATVIA":"Lettonie",
	"_LEBANON":"Liban",
	"_LESOTHO":"Lesotho",
	"_LIBERIA":"Liberia",
	"_LIBYAN_ARAB JAMAHIRIYA":"Libyan Arab Jamahiriya",
	"_LIECHTENSTEIN":"Liechtenstein",
	"_LITHUANIA":"Lituanie",
	"_LUXEMBOURG":"Luxembourg",
	"_MACAO":"Macao",
	"_MACEDONIA,_THE FORMER YUGOSLAV REPUBLIC OF":"Macédoine",
	"_MADAGASCAR":"Madagascar",
	"_MALAWI":"Malawi",
	"_MALAYSIA":"Malaisie",
	"_MALDIVES":"Maldives",
	"_MALI":"Mali",
	"_MALTA":"Malte",
	"_MARSHALL_ISLANDS":"Iles Marshall",
	"_MARTINIQUE":"Martinique",
	"_MAURITANIA":"Mauritanie",
	"_MAURITIUS":"Ile Maurice",
	"_MAYOTTE":"Mayotte",
	"_MEXICO":"Mexique",
	"_MICRONESIA,_FEDERATED STATES OF":"Micronésie",
	"_MOLDOVA,_REPUBLIC OF":"Moldavie",
	"_MONACO":"Monaco",
	"_MONGOLIA":"Mongolie",
	"_MONTENEGRO":"Monténégro",
	"_MONTSERRAT":"Montserrat",
	"_MOROCCO":"Maroc",
	"_MOZAMBIQUE":"Mozambique",
	"_MYANMAR":"Myanmar",
	"_NAMIBIA":"Namibie",
	"_NAURU":"Nauru",
	"_NEPAL":"Népal",
	"_NETHERLANDS":"Pays-Bas",
	"_NETHERLANDS_ANTILLES":"Antilles Néerlandaises",
	"_NEW_CALEDONIA":"Nouvelle-Calédonie",
	"_NEW_ZEALAND":"Nouvelle-Zélande",
	"_NICARAGUA":"Nicaragua",
	"_NIGER":"Niger",
	"_NIGERIA":"Nigéria",
	"_NIUE":"Nioué",
	"_NORFOLK_ISLAND":"Ile Norfolk",
	"_NORTHERN_MARIANA ISLANDS":"Marianne du Nord",
	"_NORWAY":"Norvège",
	"_OMAN":"Oman",
	"_PAKISTAN":"Pakistan",
	"_PALAU":"Palaos",
	"_PALESTINIAN_TERRITORY, OCCUPIED":"Palestine",
	"_PANAMA":"Panama",
	"_PAPUA_NEW GUINEA":"Papouasie Nouvelle Guinée",
	"_PARAGUAY":"Paraguay",
	"_PERU":"Pérou",
	"_PHILIPPINES":"Philippines",
	"_PITCAIRN":"Pitcairn",
	"_POLAND":"Pologne",
	"_PORTUGAL":"Portugal",
	"_PUERTO_RICO":"Porto Rico",
	"_QATAR":"Qatar",
	"_RÉUNION":"Réunion",
	"_ROMANIA":"Roumanie",
	"_RUSSIAN_FEDERATION":"Fédération de Russie",
	"_RWANDA":"Rwanda",
	"_SAINT_BARTHÃ‰LEMY":"Saint BarthÃ‰Lemy",
	"_SAINT_HELENA, ASCENSION AND TRISTAN DA CUNHA":"Saint Helena, Ascension And Tristan Da Cunha",
	"_TTS_AND NEVIS":"Saint-Kitts-et-Nevis",
	"_SAINT_LUCIA":"Sainte-Lucie",
	"_SAINT_MARTIN":"Saint-Martin",
	"_SAINT_PIERRE AND MIQUELON":"Saint-Pierre et Miquelon",
	"_SAINT_VINCENT AND THE GRENADINES":"Saint-Vincent-et-les Grenadines",
	"_SAMOA":"Samoa",
	"_SAN_MARINO":"Saint-Marin",
	"_SAO_TOME AND PRINCIPE":"Sao Tomé-et-Principe",
	"_SAUDI_ARABIA":"Arabia Saoudite",
	"_SENEGAL":"Sénégal",
	"_SERBIA":"Serbie",
	"_SEYCHELLES":"Seychelles",
	"_SIERRA_LEONE":"Sierra Leone",
	"_SINGAPORE":"Singapour",
	"_SLOVAKIA":"Slovaquie",
	"_SLOVENIA":"Slovénie",
	"_SOLOMON_ISLANDS":"Iles Salomon",
	"_SOMALIA":"Somalie",
	"_SOUTH_AFRICA":"Afrique du Sud",
	"_SOUTH_GEORGIA AND THE SOUTH SANDWICH ISLANDS":"South Georgia And The South Sandwich Islands",
	"_SPAIN":"Espagne",
	"_SRI_LANKA":"Sri Lanka",
	"_SUDAN":"Soudan",
	"_SURINAME":"Suriname",
	"_SVALBARD_AND JAN MAYEN":"Svalbard And Jan Mayen",
	"_SWAZILAND":"Swaziland",
	"_SWEDEN":"Suède",
	"_SWITZERLAND":"Suisse",
	"_SYRIAN_ARAB REPUBLIC":"Syrie",
	"_TAIWAN,_PROVINCE OF CHINA":"Taïwan",
	"_TAJIKISTAN":"Tadjikistan",
	"_TANZANIA,_UNITED REPUBLIC OF":"Tanzanie",
	"_THAILAND":"Thaïlande",
	"_TIMOR-LESTE":"Timor-Leste",
	"_TOGO":"Togo",
	"_TOKELAU":"Tokelau",
	"_TONGA":"Tonga",
	"_TRINIDAD_AND TOBAGO":"Trinité et Tobago",
	"_TUNISIA":"Tunisie",
	"_TURKEY":"Turquie",
	"_TURKMENISTAN":"Turkménistan",
	"_TURKS_AND CAICOS ISLANDS":"Turks And Caicos Islands",
	"_TUVALU":"Tuvalu",
	"_UGANDA":"Ouganda",
	"_UKRAINE":"Ukraine",
	"_UNITED_ARAB EMIRATES":"Emirats Arabes Unis",
	"_UNITED_KINGDOM":"Grande Bretagne",
	"_UNITED_STATES":"Etats Unis",
	"_UNITED_STATES MINOR OUTLYING ISLANDS":"United States Minor Outlying Islands",
	"_URUGUAY":"Uruguay",
	"_UZBEKISTAN":"Ouzbekistan",
	"_VANUATU":"Vanuatu",
	"_VATICAN_CITY STATE":"Vatican",
	"_VENEZUELA,_BOLIVARIAN REPUBLIC OF":"Vénézuela",
	"_VIET_NAM":"Vietnam",
	"_VIRGIN_ISLANDS, BRITISH":"Iles Vierges Britaniques",
	"_VIRGIN_ISLANDS, U.S.":"Iles Vierges, U.S.",
	"_WALLIS_AND FUTUNA":"Wallis et Futuna",
	"_WESTERN_SAHARA":"Sahara Occidental",
	"_YEMEN":"Yémen",
	"_ZAMBIA":"Zambie",
	"_ZIMBABWE":"Zimbabwe",
	"_SOUTHERN_SUDAN_TERRITORY,_PROVISIONAL":"Soudan du Sud",

	// Activities
	"_Agriculture":"Agriculture",
	"_Air Conditioning":"Air Conditionné",
	"_Animal Sales":"Ventes d'Animaux",
	"_Arts":"Arts",
	"_Auto Repair":"Réparation d'Automobile",
	"_Bakery":"Boulangerie",
	"_Balut-Making":"Confection de Balut",
	"_Barber Shop":"Barbier",
	"_Beauty Salon":"Salon de Beauté",
	"_Bicycle Repair":"Réparation de Bicyclettes",
	"_Bicycle Sales":"Vente de Bicyclettes",
	"_Biofuels":"Bio-carburants",
	"_Blacksmith":"Serruruer",
	"_Bookbinding":"Reliure de livres",
	"_Bookstore":"Librairie",
	"_Bricks":"Briques",
	"_Butcher Shop":"Boucher",
	"_Cafe":"Café",
	"_Call Center":"Centre d'Appels",
	"_Carpentry":"Menuiserie",
	"_Catering":"Traiteur",
	"_Cattle":"Bétail",
	"_Cement":"Ciment",
	"_Cereals":"Céréales",
	"_Charcoal Sales":"Ventes de Charbon",
	"_Cheese Making":"Fromager",
	"_Child Care":"Garde d'Enfants",
	"_Cloth and Dressmaking Supplies":"Fournitures pour la confection de vêtements",
	"_Clothing":"Vêtements",
	"_Clothing Sales":"Ventes de Vêtements",
	"_Cobbler":"Cordonnier",
	"_Computers":"Ordinateurs",
	"_Construction":"Construction",
	"_Construction Supplies":"Stocks pour la Construction",
	"_Consumer Goods":"Produits de Consommation",
	"_Cosmetics Sales":"Ventes de Produits Cosmétiques",
	"_Crafts":"Artisanat",
	"_Dairy":"Laiterie",
	"_Decorations Sales":"Ventes de Produits pour la Decoration",
	"_Dental":"Dentiste",
	"_Electrical Goods":"Produits Electriques",
	"_Electrician":"Electricien",
	"_Electronics Repair":"Réparations de Produits Electroniques",
	"_Electronics Sales":"Ventes de Produits Electroniques",
	"_Embroidery":"Broderie",
	"_Energy Efficiency":"Efficacité Energétique",
	"_Entertainment":"Divertissement",
	"_Farm Supplies":"Stocks pour l'Exploitation Agricole",
	"_Farming":"Exploitation Agricole",
	"_Film":"Film",
	"_Fish Selling":"Ventes de Poissons",
	"_Fishing":"Pêche",
	"_Flowers":"Fleurs",
	"_Food":"Alimentation",
	"_Food Market":"Marché",
	"_Food Production/Sales":"Produits Alimentaires/Ventes",
	"_Food Stall":"Echoppe",
	"_Fruits and Vegetables":"Fruits et Légumes",
	"_Fuel/Firewood":"Carburant/Bois à Brûler",
	"_Funeral Expenses":"Dépenses pour des Obsèques",
	"_Furniture Making":"Furniture Making",
	"_Games":"Jeux",
	"_General Store":"Bazar",
	"_Goods Distribution":"Distribution",
	"_Green":"Développement Durable",
	"_Grocery Store":"Epicerie",
	"_Hardware":"Quincaillerie",
	"_Health":"Santé",
	"_Home Appliances":"Appareils Ménagers",
	"_Home Products Sales":"Ventes de Produits pour la Maison",
	"_Hotel":"Hôtelerie",
	"_Internet Cafe":"Cyber Café",
	"_Jewelry":"Bijouterie",
	"_Knitting":"Tricot",
	"_Land Rental":"Location de Terrain",
	"_Laundry":"Buanderie",
	"_Liquor Store / Off-License":"Marchant de Vins et Spiritueux",
	"_Livestock":"Bétail",
	"_Machine Shop":"Atelier",
	"_Machinery Rental":"Location de Machines",
	"_Manufacturing":"Confection",
	"_Medical Clinic":"Clinique Médicale",
	"_Metal Shop":"Ferronnier",
	"_Milk Sales":"Ventes de Lait",
	"_Mobile Phones":"Téléphones Portable",
	"_Motorcycle Repair":"Réparation de Motos",
	"_Motorcycle Transport":"Transport en Moto",
	"_Movie Tapes and DVDs":"Films Cassettes Vidéo et DVD",
	"_Music Discs and Tapes":"Musiques Disques et Cassettes",
	"_Musical Instruments":"Instruments de Musique",
	"_Musical Performance":"Performance Musicale",
	"_Natural Medicines":"Médicaments Naturels",
	"_Office Supplies":"Fournitures de Bureau",
	"_Paper Sales":"Ventes de Papier",
	"_Party Supplies":"Articles de Fêtes",
	"_Patchwork":"Patchwork",
	"_Perfumes":"Parfums",
	"_Personal Education Expenses":"Dépenses Personnelles pour l'Education",
	"_Personal Housing Expenses":"Dépenses Personnelles de Logement",
	"_Personal Medical Expenses":"Dépenses Personnelles pour les Soins Médicaux",
	"_Personal Products Sales":"Ventes de Produits Personnels",
	"_Personal Purchases":"Achats Personnels",
	"_Pharmacy":"Pharmacie",
	"_Phone Accessories":"Accessoires pour le Téléphone",
	"_Phone Repair":"Réparations de Téléphones",
	"_Phone Use Sales":"Ventes Utilisation de Téléphone",
	"_Photography":"Photographie",
	"_Pigs":"Porc",
	"_Plastics Sales":"Ventes de Plastiques",
	"_Poultry":"Volaille",
	"_Printing":"Impression",
	"_Property":"Propriété",
	"_Pub":"Pub",
	"_Quarrying":"Extraction",
	"_Recycling":"Recyclage",
	"_Religious Articles":"Articles Religieux",
	"_Restaurant":"Restaurant",
	"_Retail":"Vente au Détail",
	"_Rickshaw":"Pousse-Pousse",
	"_Secretarial Services":"Services de Secrétariat",
	"_Services":"Services",
	"_Sewing":"Couture",
	"_Shoe Sales":"Ventes de Chaussures",
	"_Soft Drinks":"Boissons Non Alcoolisées",
	"_Solar Power":"Energie Solaire",
	"_Souvenir Sales":"Ventes d'Objets de Souvenir",
	"_Spare Parts":"Pièces de Rechange",
	"_Sporting Good Sales":"Ventes d'Articles de Sport",
	"_Tailoring":"Façonnage",
	"_Taxi":"Taxi",
	"_Teaching and Schools":"Enseigement",
	"_Textiles":"Textiles",
	"_Timber Sales":"Ventes de Bois",
	"_Tourism":"Tourisme",
	"_Transportation":"Transports",
	"_Traveling Sales":"Ventes de Voyage",
	"_Upholstery":"Revêtement",
	"_Used Clothing":"Vêtements Usagés",
	"_Utilities":"Charges",
	"_Vehicle":"Véhicule",
	"_Vehicle Repairs":"Réparation de Véhicules",
	"_Veterinary Sales":"Vétérinaire",
	"_Waste Management":"Gestion des Déchêts",
	"_Water Distribution":"Distribution d'Eau",
	"_Weaving":"Tissage",
	"_Wedding Expenses":"Dépenses de Mariage",
	"_Well digging":"Creusage de Puit",
	"_Wholesale":"Vente de Gros",
		
	// Sectors
	"_Agriculture":"Agriculture",
	"_Arts":"Arts",
	"_Clothing":"Vêtements",
	"_Construction":"Construction",
	"_Education":"Education",
	"_Entertainment":"Divertissement",
	"_Food":"Alimentation",
	"_Green":"Développement Durable",
	"_Health":"Santé",
	"_Housing":"Habitation",
	"_Manufacturing":"Confection",
	"_Personal_Use":"Usage Personnel",
	"_Retail":"Vente de Détail",
	"_Services":"Services",
	"_Transportation":"Transports",
	"_Wholesale":"Vente de Gros",

	// ABOUT
	"_What_is_Kiva?":"Qu’est Kiva?",
	"*aboutContent":'<p>La mission de Kiva est de mettre en relation des personnes par l’intermédiaire d’emprunts afin de réduire la pauvreté dans le monde.</p>\n\n<p>Kiva permet aux individus de prêter de l’argent à un microentrepreneur à l’autre bout du monde. En combinant la microfinance et l’Internet, Kiva est en train de créer une communauté mondiale de personnes liées par des prêts.</p>\n\n<div class=\'kiva-figureRight\'>\n	    		<a  href="http://www.kiva.org/lend/23303" target="_blank" ><img  border="0" src="http://www.kiva.org/images/Pendo.jpg" class="scaled" /></a>\n\n<p><a href="http://www.kiva.org/lend/23303">Pendo Luisi</a>, 27 years old, borrowed $175 to open a cafe in Dar es Salaam, Tanzania.</p>\n  </div>\n\n<p>Kiva est né des convictions suivantes:\n<ul>\n<li>les personnes sont par nature généreuses et vont aider d’autres personnes si l’opportunité de le faire de manière transparente et responsable leur est offerte</li>\n<li>Les personnes démunies sont très motivées et peuvent donc réussir si l’opportunité de le faire leur est offerte</li>\n<li>En connectant les personnes les unes avec les autres, on peut créer des relations qui vont au-delà de la transaction financière, et on peut construire une communauté globale de soutien et d’encouragement pour chacun</li>\n</ul>\n</p>\n\n<p>Kiva promeut:\n<ul>\n<li>Dignité: Kiva encourage la création de relation de partenariat, plutôt que de bienfaiteur. Les relations en partenariat sont caractérisées par dignité et respect mutuels</li>\n<li>Responsabilité: Les prêts encouragent plus la prise de responsabilité que les donations, qui ne demandent pas à être remboursées</li>\n<li>Transparence: Le site web de Kiva est une plateforme ouverte où la communication peut se faire librement partout dans le monde</li>\n</ul>\n</p>',
}) ;
