// ==========================================================================
// Project:   Klb
// Copyright: ©2009 Kiva Microfunds
// Licensed under MIT License Terms (see license.js)
// ==========================================================================
/*globals Klb */

// Place strings you want to localize here.  In your app, use the key and
// localize it using "key string".loc().  HINT: For your key names, use the
// english string with an underscore in front.  This way you can still see
// how your UI will look and you'll notice right away when something needs a
// localized string added to this file!
//
SC.stringsFor('English', {
  // "_String Key": "Localized String"
	"__INTL__":"en",

	//// General
	"_KlbTitle": "Kiva Translated",
	"_OK": "OK",
	"_Edit": "Edit",
	
	//// Primary Sections
	"_About": "About",
	"_Projects": "Projects",
	"_Learn_More": "Learn More",
	"_Register": "Register",
	"_Demo": "Demo",

	"_Choose_A_Loan": "Choose A Loan",
	'_Get started now by finding an entrepreneur and making a loan!':'Get started now by finding an entrepreneur and making a loan!',
		
	//// Basket
	"_Checkout": "Checkout",

	// sort drop down
	"_Sort_by": "Sort by",
	"_Loan_Amount": "Loan Amount",
	"_Amount_Remaining": "Amount Remaining",
	"_sb:Expiring Soon": "Expiring Soon",
	"_Most_Recent": "Most Recent",
	"_List_Grid":"List Grid",
	"_List":"List",
	
	/// Sidebar
	'_Explore':'Explore',
	'_Getting Started':'Getting Started',
	'_Browse All Loans':'Browse All Loans',
	'_Sample Filters':'Sample Filters',
	'_African Farmers':'African Farmers',
	'_African Women':'African Women',
	'_Educational Loans':'Educational Loans',
	'_Francophone Countries':'Francophone Countries',
	'_Expiring Soon':'Expiring Soon',
	
	"_Filter Options":"Filter Options",
	"_Search": "Search (coming soon)",
  "_Countries": "Countries",
  "_Sectors": "Sectors",
  "_Gender": "Gender",
  "_Female": "Female",
  "_Male": "Male",
  "_Gender": "Gender",
  "_Sector": "Sector",
  "_Borrowers": "Borrowers",
  "_Partner_Rating": "Minimum Partner Rating",
  "_Groups": "Groups",
  "_Individuals": "Individuals",
  "_Reset": "Reset",
  "_Save": "Save",
  "_All": "All",

	// Countries Popup
	"_Choose Countries":"Choose Countries",

	// Sectors Popup
	"_Choose Sectors":"Choose Sectors",
	
	// Results area
	"_loans found":"loans found",
	"_loan found":"loan found",

	"_Finding Available Loans":"Finding Available Loans…",
	"_No Loans Matched Your Criteria":"No Loans Matched Your Criteria",
	"_Please choose another filter or change your filter options.":"Please choose another filter or change your filter options.",
	
	//loan_list_item"
	"_Loan_Use":"Loan Use",
	"_Country": "Country",
	"_Rating": "Rating",
	"_Needed_Out_Of":"needed out of",
	"_Lend $25":"Lend $25",
	
	// Countries
	"_AFGHANISTAN":"Afghanistan",
	"_ÅLAND_ISLANDS":"Åland Islands",
	"_ALBANIA":"Albania",
	"_ALGERIA":"Algeria",
	"_AMERICAN_SAMOA":"American Samoa",
	"_ANDORRA":"Andorra",
	"_ANGOLA":"Angola",
	"_ANGUILLA":"Anguilla",
	"_ANTARCTICA":"Antarctica",
	"_ANTIGUA_AND BARBUDA":"Antigua And Barbuda",
	"_ARGENTINA":"Argentina",
	"_ARMENIA":"Armenia",
	"_ARUBA":"Aruba",
	"_AUSTRALIA":"Australia",
	"_AUSTRIA":"Austria",
	"_AZERBAIJAN":"Azerbaijan",
	"_BAHAMAS":"Bahamas",
	"_BAHRAIN":"Bahrain",
	"_BANGLADESH":"Bangladesh",
	"_BARBADOS":"Barbados",
	"_BELARUS":"Belarus",
	"_BELGIUM":"Belgium",
	"_BELIZE":"Belize",
	"_BENIN":"Benin",
	"_BERMUDA":"Bermuda",
	"_BHUTAN":"Bhutan",
	"_BOLIVIA,_PLURINATIONAL STATE OF":"Bolivia",
	"_BOSNIA_AND HERZEGOVINA":"Bosnia And Herzegovina",
	"_BOTSWANA":"Botswana",
	"_BOUVET_ISLAND":"Bouvet Island",
	"_BRAZIL":"Brazil",
	"_BRITISH_INDIAN OCEAN TERRITORY":"British Indian Ocean Territory",
	"_BRUNEI_DARUSSALAM":"Brunei Darussalam",
	"_BULGARIA":"Bulgaria",
	"_BURKINA_FASO":"Burkina Faso",
	"_BURUNDI":"Burundi",
	"_CAMBODIA":"Cambodia",
	"_CAMEROON":"Cameroon",
	"_CANADA":"Canada",
	"_CAPE_VERDE":"Cape Verde",
	"_CAYMAN_ISLANDS":"Cayman Islands",
	"_CENTRAL_AFRICAN REPUBLIC":"Central African Republic",
	"_CHAD":"Chad",
	"_CHILE":"Chile",
	"_CHINA":"China",
	"_CHRISTMAS_ISLAND":"Christmas Island",
	"_COCOS_(KEELING)_ISLANDS":"Cocos Islands",
	"_COLOMBIA":"Colombia",
	"_COMOROS":"Comoros",
	"_CONGO":"Congo",
	"_CONGO,_THE DEMOCRATIC REPUBLIC OF THE":"Congo",
	"_COOK_ISLANDS":"Cook Islands",
	"_COSTA_RICA":"Costa Rica",
	"_CÔTE_D'IVOIRE":"Ivory Coast",
	"_CROATIA":"Croatia",
	"_CUBA":"Cuba",
	"_CYPRUS":"Cyprus",
	"_CZECH_REPUBLIC":"Czech Republic",
	"_DENMARK":"Denmark",
	"_DJIBOUTI":"Djibouti",
	"_DOMINICA":"Dominica",
	"_DOMINICAN_REPUBLIC":"Dominican Republic",
	"_ECUADOR":"Ecuador",
	"_EGYPT":"Egypt",
	"_EL_SALVADOR":"El Salvador",
	"_EQUATORIAL_GUINEA":"Equatorial Guinea",
	"_ERITREA":"Eritrea",
	"_ESTONIA":"Estonia",
	"_ETHIOPIA":"Ethiopia",
	"_FALKLAND_ISLANDS_(MALVINAS)":"Falkland Islands",
	"_FAROE_ISLANDS":"Faroe Islands",
	"_FIJI":"Fiji",
	"_FINLAND":"Finland",
	"_FRANCE":"France",
	"_FRENCH_GUIANA":"French Guiana",
	"_FRENCH_POLYNESIA":"French Polynesia",
	"_FRENCH_SOUTHERN TERRITORIES":"French Southern Territories",
	"_GABON":"Gabon",
	"_GAMBIA":"Gambia",
	"_GEORGIA":"Georgia",
	"_GERMANY":"Germany",
	"_GHANA":"Ghana",
	"_GIBRALTAR":"Gibraltar",
	"_GREECE":"Greece",
	"_GREENLAND":"Greenland",
	"_GRENADA":"Grenada",
	"_GUADELOUPE":"Guadeloupe",
	"_GUAM":"Guam",
	"_GUATEMALA":"Guatemala",
	"_GUERNSEY":"Guernsey",
	"_GUINEA":"Guinea",
	"_GUINEA-BISSAU":"Guinea-Bissau",
	"_GUYANA":"Guyana",
	"_HAITI":"Haiti",
	"_HEARD_ISLAND AND MCDONALD ISLANDS":"Heard Island And Mcdonald Islands",
	"_HONDURAS":"Honduras",
	"_HONG_KONG":"Hong Kong",
	"_HUNGARY":"Hungary",
	"_ICELAND":"Iceland",
	"_INDIA":"India",
	"_INDONESIA":"Indonesia",
	"_IRAN,_ISLAMIC REPUBLIC OF":"Iran",
	"_IRAQ":"Iraq",
	"_IRELAND":"Ireland",
	"_ISLE_OF MAN":"Isle Of Man",
	"_ISRAEL":"Israel",
	"_ITALY":"Italy",
	"_JAMAICA":"Jamaica",
	"_JAPAN":"Japan",
	"_JERSEY":"Jersey",
	"_JORDAN":"Jordan",
	"_KAZAKHSTAN":"Kazakhstan",
	"_KENYA":"Kenya",
	"_KIRIBATI":"Kiribati",
	"_KOREA,_DEMOCRATIC PEOPLE'S REPUBLIC OF":"South Korea",
	"_KOREA,_REPUBLIC OF":"North Korea",
	"_KUWAIT":"Kuwait",
	"_KYRGYZSTAN":"Kyrgyzstan",
	"_LAO_PEOPLE'S DEMOCRATIC REPUBLIC":"Laos",
	"_LATVIA":"Latvia",
	"_LEBANON":"Lebanon",
	"_LESOTHO":"Lesotho",
	"_LIBERIA":"Liberia",
	"_LIBYAN_ARAB JAMAHIRIYA":"Libyan Arab Jamahiriya",
	"_LIECHTENSTEIN":"Liechtenstein",
	"_LITHUANIA":"Lithuania",
	"_LUXEMBOURG":"Luxembourg",
	"_MACAO":"Macao",
	"_MACEDONIA,_THE FORMER YUGOSLAV REPUBLIC OF":"Macedonia",
	"_MADAGASCAR":"Madagascar",
	"_MALAWI":"Malawi",
	"_MALAYSIA":"Malaysia",
	"_MALDIVES":"Maldives",
	"_MALI":"Mali",
	"_MALTA":"Malta",
	"_MARSHALL_ISLANDS":"Marshall Islands",
	"_MARTINIQUE":"Martinique",
	"_MAURITANIA":"Mauritania",
	"_MAURITIUS":"Mauritius",
	"_MAYOTTE":"Mayotte",
	"_MEXICO":"Mexico",
	"_MICRONESIA,_FEDERATED STATES OF":"Micronesia",
	"_MOLDOVA,_REPUBLIC OF":"Moldova",
	"_MONACO":"Monaco",
	"_MONGOLIA":"Mongolia",
	"_MONTENEGRO":"Montenegro",
	"_MONTSERRAT":"Montserrat",
	"_MOROCCO":"Morocco",
	"_MOZAMBIQUE":"Mozambique",
	"_MYANMAR":"Myanmar",
	"_NAMIBIA":"Namibia",
	"_NAURU":"Nauru",
	"_NEPAL":"Nepal",
	"_NETHERLANDS":"Netherlands",
	"_NETHERLANDS_ANTILLES":"Netherlands Antilles",
	"_NEW_CALEDONIA":"New Caledonia",
	"_NEW_ZEALAND":"New Zealand",
	"_NICARAGUA":"Nicaragua",
	"_NIGER":"Niger",
	"_NIGERIA":"Nigeria",
	"_NIUE":"Niue",
	"_NORFOLK_ISLAND":"Norfolk Island",
	"_NORTHERN_MARIANA ISLANDS":"Northern Mariana Islands",
	"_NORWAY":"Norway",
	"_OMAN":"Oman",
	"_PAKISTAN":"Pakistan",
	"_PALAU":"Palau",
	"_PALESTINIAN_TERRITORY, OCCUPIED":"Palestine",
	"_PANAMA":"Panama",
	"_PAPUA_NEW GUINEA":"Papua New Guinea",
	"_PARAGUAY":"Paraguay",
	"_PERU":"Peru",
	"_PHILIPPINES":"Philippines",
	"_PITCAIRN":"Pitcairn",
	"_POLAND":"Poland",
	"_PORTUGAL":"Portugal",
	"_PUERTO_RICO":"Puerto Rico",
	"_QATAR":"Qatar",
	"_RÉUNION":"RÉUnion",
	"_ROMANIA":"Romania",
	"_RUSSIAN_FEDERATION":"Russian Federation",
	"_RWANDA":"Rwanda",
	"_SAINT_BARTHÉLEMY":"Saint BarthÉLemy",
	"_SAINT_HELENA, ASCENSION AND TRISTAN DA CUNHA":"Saint Helena, Ascension And Tristan Da Cunha",
	"_TTS_AND NEVIS":"Tts And Nevis",
	"_SAINT_LUCIA":"Saint Lucia",
	"_SAINT_MARTIN":"Saint Martin",
	"_SAINT_PIERRE AND MIQUELON":"Saint Pierre And Miquelon",
	"_SAINT_VINCENT AND THE GRENADINES":"Saint Vincent And The Grenadines",
	"_SAMOA":"Samoa",
	"_SAN_MARINO":"San Marino",
	"_SAO_TOME AND PRINCIPE":"Sao Tome And Principe",
	"_SAUDI_ARABIA":"Saudi Arabia",
	"_SENEGAL":"Senegal",
	"_SERBIA":"Serbia",
	"_SEYCHELLES":"Seychelles",
	"_SIERRA_LEONE":"Sierra Leone",
	"_SINGAPORE":"Singapore",
	"_SLOVAKIA":"Slovakia",
	"_SLOVENIA":"Slovenia",
	"_SOLOMON_ISLANDS":"Solomon Islands",
	"_SOMALIA":"Somalia",
	"_SOUTH_AFRICA":"South Africa",
	"_SOUTH_GEORGIA AND THE SOUTH SANDWICH ISLANDS":"South Georgia And The South Sandwich Islands",
	"_SPAIN":"Spain",
	"_SRI_LANKA":"Sri Lanka",
	"_SUDAN":"Sudan",
	"_SURINAME":"Suriname",
	"_SVALBARD_AND JAN MAYEN":"Svalbard And Jan Mayen",
	"_SWAZILAND":"Swaziland",
	"_SWEDEN":"Sweden",
	"_SWITZERLAND":"Switzerland",
	"_SYRIAN_ARAB REPUBLIC":"Syrian Arab Republic",
	"_TAIWAN,_PROVINCE OF CHINA":"Taiwan",
	"_TAJIKISTAN":"Tajikistan",
	"_TANZANIA,_UNITED_REPUBLIC_OF":"Tanzania",
	"_THAILAND":"Thailand",
	"_TIMOR-LESTE":"Timor-Leste",
	"_TOGO":"Togo",
	"_TOKELAU":"Tokelau",
	"_TONGA":"Tonga",
	"_TRINIDAD_AND TOBAGO":"Trinidad And Tobago",
	"_TUNISIA":"Tunisia",
	"_TURKEY":"Turkey",
	"_TURKMENISTAN":"Turkmenistan",
	"_TURKS_AND CAICOS ISLANDS":"Turks And Caicos Islands",
	"_TUVALU":"Tuvalu",
	"_UGANDA":"Uganda",
	"_UKRAINE":"Ukraine",
	"_UNITED_ARAB EMIRATES":"United Arab Emirates",
	"_UNITED_KINGDOM":"United Kingdom",
	"_UNITED_STATES":"United States",
	"_UNITED_STATES MINOR OUTLYING ISLANDS":"United States Minor Outlying Islands",
	"_URUGUAY":"Uruguay",
	"_UZBEKISTAN":"Uzbekistan",
	"_VANUATU":"Vanuatu",
	"_VATICAN_CITY STATE":"Vatican City",
	"_VENEZUELA,_BOLIVARIAN REPUBLIC OF":"Venezuela",
	"_VIET_NAM":"Viet Nam",
	"_VIRGIN_ISLANDS, BRITISH":"Virgin Islands, British",
	"_VIRGIN_ISLANDS, U.S.":"Virgin Islands, U.S.",
	"_WALLIS_AND FUTUNA":"Wallis And Futuna",
	"_WESTERN_SAHARA":"Western Sahara",
	"_YEMEN":"Yemen",
	"_ZAMBIA":"Zambia",
	"_ZIMBABWE":"Zimbabwe",
	"_SOUTHERN_SUDAN_TERRITORY,_PROVISIONAL":"Southern Sudan",
	
	// Activities
	"_Agriculture":"Agriculture",
	"_Air Conditioning":"Air Conditioning",
	"_Animal Sales":"Animal Sales",
	"_Arts":"Arts",
	"_Auto Repair":"Auto Repair",
	"_Bakery":"Bakery",
	"_Balut-Making":"Balut-Making",
	"_Barber Shop":"Barber Shop",
	"_Beauty Salon":"Beauty Salon",
	"_Bicycle Repair":"Bicycle Repair",
	"_Bicycle Sales":"Bicycle Sales",
	"_Biofuels":"Biofuels",
	"_Blacksmith":"Blacksmith",
	"_Bookbinding":"Bookbinding",
	"_Bookstore":"Bookstore",
	"_Bricks":"Bricks",
	"_Butcher Shop":"Butcher Shop",
	"_Cafe":"Cafe",
	"_Call Center":"Call Center",
	"_Carpentry":"Carpentry",
	"_Catering":"Catering",
	"_Cattle":"Cattle",
	"_Cement":"Cement",
	"_Cereals":"Cereals",
	"_Charcoal Sales":"Charcoal Sales",
	"_Cheese Making":"Cheese Making",
	"_Child Care":"Child Care",
	"_Cloth & Dressmaking Supplies":"Cloth & Dressmaking Supplies",
	"_Clothing":"Clothing",
	"_Clothing Sales":"Clothing Sales",
	"_Cobbler":"Cobbler",
	"_Computers":"Computers",
	"_Construction":"Construction",
	"_Construction Supplies":"Construction Supplies",
	"_Consumer Goods":"Consumer Goods",
	"_Cosmetics Sales":"Cosmetics Sales",
	"_Crafts":"Crafts",
	"_Dairy":"Dairy",
	"_Decorations Sales":"Decorations Sales",
	"_Dental":"Dental",
	"_Electrical Goods":"Electrical Goods",
	"_Electrician":"Electrician",
	"_Electronics Repair":"Electronics Repair",
	"_Electronics Sales":"Electronics Sales",
	"_Embroidery":"Embroidery",
	"_Energy Efficiency":"Energy Efficiency",
	"_Entertainment":"Entertainment",
	"_Farm Supplies":"Farm Supplies",
	"_Farming":"Farming",
	"_Film":"Film",
	"_Fish Selling":"Fish Selling",
	"_Fishing":"Fishing",
	"_Flowers":"Flowers",
	"_Food":"Food",
	"_Food Market":"Food Market",
	"_Food Production/Sales":"Food Production/Sales",
	"_Food Stall":"Food Stall",
	"_Fruits & Vegetables":"Fruits & Vegetables",
	"_Fuel/Firewood":"Fuel/Firewood",
	"_Funeral Expenses":"Funeral Expenses",
	"_Furniture Making":"Furniture Making",
	"_Games":"Games",
	"_General Store":"General Store",
	"_Goods Distribution":"Goods Distribution",
	"_Green":"Green",
	"_Grocery Store":"Grocery Store",
	"_Hardware":"Hardware",
	"_Health":"Health",
	"_Home Appliances":"Home Appliances",
	"_Home Products Sales":"Home Products Sales",
	"_Hotel":"Hotel",
	"_Internet Cafe":"Internet Cafe",
	"_Jewelry":"Jewelry",
	"_Knitting":"Knitting",
	"_Land Rental":"Land Rental",
	"_Laundry":"Laundry",
	"_Liquor Store / Off-License":"Liquor Store / Off-License",
	"_Livestock":"Livestock",
	"_Machine Shop":"Machine Shop",
	"_Machinery Rental":"Machinery Rental",
	"_Manufacturing":"Manufacturing",
	"_Medical Clinic":"Medical Clinic",
	"_Metal Shop":"Metal Shop",
	"_Milk Sales":"Milk Sales",
	"_Mobile Phones":"Mobile Phones",
	"_Motorcycle Repair":"Motorcycle Repair",
	"_Motorcycle Transport":"Motorcycle Transport",
	"_Movie Tapes and DVDs":"Movie Tapes and DVDs",
	"_Music Discs and Tapes":"Music Discs and Tapes",
	"_Musical Instruments":"Musical Instruments",
	"_Musical Performance":"Musical Performance",
	"_Natural Medicines":"Natural Medicines",
	"_Office Supplies":"Office Supplies",
	"_Paper Sales":"Paper Sales",
	"_Party Supplies":"Party Supplies",
	"_Patchwork":"Patchwork",
	"_Perfumes":"Perfumes",
	"_Family Education Expenses":"Family Education Expenses",
	"_Personal Education Expenses":"Personal Education Expenses",
	"_Personal Student Loan":"Personal Student Loan",
	"_Personal Housing Expenses":"Personal Housing Expenses",
	"_Personal Medical Expenses":"Personal Medical Expenses",
	"_Personal Products Sales":"Personal Products Sales",
	"_Personal Purchases":"Personal Purchases",
	"_Pharmacy":"Pharmacy",
	"_Phone Accessories":"Phone Accessories",
	"_Phone Repair":"Phone Repair",
	"_Phone Use Sales":"Phone Use Sales",
	"_Photography":"Photography",
	"_Pigs":"Pigs",
	"_Plastics Sales":"Plastics Sales",
	"_Poultry":"Poultry",
	"_Printing":"Printing",
	"_Property":"Property",
	"_Pub":"Pub",
	"_Quarrying":"Quarrying",
	"_Recycling":"Recycling",
	"_Religious Articles":"Religious Articles",
	"_Restaurant":"Restaurant",
	"_Retail":"Retail",
	"_Rickshaw":"Rickshaw",
	"_Secretarial Services":"Secretarial Services",
	"_Services":"Services",
	"_Sewing":"Sewing",
	"_Shoe Sales":"Shoe Sales",
	"_Soft Drinks":"Soft Drinks",
	"_Solar Power":"Solar Power",
	"_Souvenir Sales":"Souvenir Sales",
	"_Spare Parts":"Spare Parts",
	"_Sporting Good Sales":"Sporting Good Sales",
	"_Tailoring":"Tailoring",
	"_Taxi":"Taxi",
	"_Teaching and Schools":"Teaching and Schools",
	"_Textiles":"Textiles",
	"_Timber Sales":"Timber Sales",
	"_Tourism":"Tourism",
	"_Transportation":"Transportation",
	"_Traveling Sales":"Traveling Sales",
	"_Upholstery":"Upholstery",
	"_Used Clothing":"Used Clothing",
	"_Utilities":"Utilities",
	"_Vehicle":"Vehicle",
	"_Vehicle Repairs":"Vehicle Repairs",
	"_Veterinary Sales":"Veterinary Sales",
	"_Waste Management":"Waste Management",
	"_Water Distribution":"Water Distribution",
	"_Weaving":"Weaving",
	"_Wedding Expenses":"Wedding Expenses",
	"_Well digging":"Well digging",
	"_Wholesale":"Wholesale",
	
	// Sectors
	"_Agriculture":"Agriculture",
	"_Arts":"Arts",
	"_Clothing":"Clothing",
	"_Construction":"Construction",
	"_Education":"Education",
	"_Entertainment":"Entertainment",
	"_Food":"Food",
	"_Green":"Green",
	"_Health":"Health",
	"_Housing":"Housing",
	"_Manufacturing":"Manufacturing",
	"_Personal_Use":"Personal Use",
	"_Retail":"Retail",
	"_Services":"Services",
	"_Transportation":"Transportation",
	"_Wholesale":"Wholesale",
	

	//////////////////////////////////////////////
	// PREHOME
	
	// Headers
	'_The Situation':'The Situation',
	'_In Numbers':'In Numbers',
	
	// Captions
	'_something about why to click the browse CTA':'',
	'_Kiva. Make a loan, change a life.':'Kiva. Make a loan, change a life.',

	// Borrower Story
	'_An entrepreneur needs a loan to grow her business':'An entrepreneur needs a loan to grow her business',
	'_Kiva works with local partners who specialize in microcredit':'Kiva works with local partners who specialize in microcredit',
	'_People from all over the world become lenders, helping in big ways with small amounts of money':'People from all over the world become lenders, helping in big ways with small amounts of money',

	// Lender Story
	'_Make the choice to change a life':'Make the choice to change a life',
	'_Get repaid':'Get repaid',
	'_Become part of the Kiva community':'Become part of the Kiva community',
	
	//////////////////////////////////////////////
	// ABOUT
	
	// Headers
	'_How Microfinance Began':'How Microfinance Began',
	'_What Is Kiva?':'What Is Kiva?',
	'_Why Kiva en Français?':'Why Kiva en Français?',
	'_Contact':'Contact',
	'_Our Partners':'Our Partners',

	// Figures
	'_in loans':'in loans',
	'_entrepreneurs helped':'entrepreneurs helped',
	'_countries':'countries',
	'_partners':'partners',

	// Captions
	'_Kiva connects people through lending to alleviate poverty.':'Kiva connects people through lending to alleviate poverty.',
	'*about_captionYunus1':'“Give a man a fish, you feed him for a day… Teach a man to fish and you feed him for a lifetime.”',
	'*about_captionYunus2':'But, what if he can‘t afford a net?',

	'*mfHow_para_1':"Microfinance was developed in Bangladesh by economics professor Muhammad Yunus, recipient of the 2006 Nobel Peace Prize.",
	'*mfHow_para_2':"The concept is to make small loans available to entrepreneurs who are not able to access loans from traditional banks.",
	'*mfHow_para_3':"It has allowed millions of people in developing countries to lift themselves out of poverty, making their proposed projects a reality and creating wealth.",
	'*mfHow_para_4':"This grand social innovation is now spreading itself to other developing countries and areas of simlar transition.",
	
	'*kivaWhat_para_1':"Kiva.org is the first online microfinance organization in the world, financing loans for over 500 projects a day.",
	'*kivaWhat_para_2':"This success story, founded in San Francisco in 2005, has already raised over 100M€ in loans in over 55 different countries.",
	'*kivaWhat_para_3':"Kiva has rigourously selected over 100 microfinance institutions (MFI) who are its partners in the field and together have an average repayment rate of over 98%.",
	'*kivaWhat_para_4':"Over the course of the loan, the lenders are repaid which allows them to withdraw this money or reinvest it in new projects.",

	'*kefWhy_para_1':"The idea is to promote microfinance thanks to the fancophile community, creating a website in French allowing the selection of projects to finance on Kiva",
	'*kefWhy_para_2':"The creators of the french website are friends and alumni of Kiva who wish to share their enthusiasm.",
	'*kefWhy_para_3':"Once you select the rpojects you wish to support, your loan is finalized on the Kiva website.",

	//////////////////////////////////////////////
	// REGISTER
	
	'*reg_disclaimer_text1':'Pour valider votre investissement, vous devez avoir un compte d’utilisateur Kiva. Ce processus est en anglais mais un accompagnement en français est à votre disposition à gauche de l’écran. Une fois votre compte ouvert, vous serez redirigé sur kiva.org pour compléter votre paiement.',
	'*reg_disclaimer_text2':'Si vous possédez déjà un compte kiva, vous serez redirigé sur le site kiva.org où vous pourrez vous connecter à votre compte pour compléter votre paiement.',
	
	'_Loading Kiva Website':'Loading Kiva Website…',
	'_Help':'Help',
	'_Use of the english site':'Use of the english site',
	
	'_Enter your first name':'Enter your first name',
	'_Enter your last name':'Enter your last name',
	'_Enter your email address':'Enter your email address',
	'_Re-enter your email address':'Re-enter your email address',
	'_Choose a password between 6 and 12 characters':'Choose a password between 6 and 12 characters',
	'_Confirm the password you chose':'Confirm the password you chose',
	'_If your friend recommended you to loan on Kiva, please enter their email address so that Kiva can thank them!':'If your friend recommended you to loan on Kiva, please enter their email address so that Kiva can thank them!',

//////////////////////////////////////////////
// DEMOS

	'_The Pedro Story':'The Pedro Story',
	'_Demos coming soon… for now, enjoy this introduction to Kiva through the story of Pedro, a farmer in Boliva:':'Demos coming soon… for now, enjoy this introduction to Kiva through the story of Pedro, a farmer in Boliva:'

}) ;
