// ==========================================================================
// Project:   Klb
// Copyright: ©2009 Kiva Microfunds
// Licensed under MIT License Terms (see license.js)
// ==========================================================================
/*globals Klb */

// Place strings you want to localize here.  In your app, use the key and
// localize it using "key string".loc().  HINT: For your key names, use the
// english string with an underscore in front.  This way you can still see
// how your UI will look and you'll notice right away when something needs a
// localized string added to this file!
//
SC.stringsFor('English', {
  // "_String Key": "Localized String"

	//// General
	"_KlbTitle": "Loanr",
	"_OK": "OK",
	"_Edit": "Edit",
	
	//// Primary Sections
	"_About": "About",
	"_Choose_A_Loan": "Choose A Loan",
	"_Learn_More": "Learn More",
	"_Register": "Register",
	"_Demo": "Demo",
	
	//// Chrome
	"_Checkout": "Checkout",
	// sort drop down
	"_Sort_by": "Sort by",
	"_Loan_Amount": "Loan Amount",
	"_Amount_Remaining": "Amount Remaining",
	"_Expiring_Soon": "Expiring Soon",
	"_Most_Recent": "Most Recent",
	"_List_Grid":"List Grid",
	"_List":"List",
	
	/// Sidebar
	"_Filter Options":"Filter Options",
	"_Search": "Search",
  "_Countries": "Countries",
  "_Sectors": "Sectors",
  "_Gender": "Gender",
  "_Female": "Female",
  "_Male": "Male",
  "_Gender": "Gender",
  "_Sector": "Sector",
  "_Borrowers": "Borrowers Per Loan",
  "_Partner_Rating": "Minimum Partner Rating",
  "_Groups": "Groups",
  "_Reset": "Reset",
  "_Save": "Save",

	// Countries Popup
	"_Choose Countries":"Choose Countries",

	// Sectors Popup
	"_Choose Sectors":"Choose Sectors",
	
	//loan_list_item"
	"_Loan_Use":"Loan Use",
	"_Country": "Country",
	"_Rating": "Rating",
	"_Needed_Out_Of":"needed out of",
	
	// Countries
	"_AFGHANISTAN":"Afghanistan",
	"_ÅLAND_ISLANDS":"Åland Islands",
	"_ALBANIA":"Albania",
	"_ALGERIA":"Algeria",
	"_AMERICAN_SAMOA":"American Samoa",
	"_ANDORRA":"Andorra",
	"_ANGOLA":"Angola",
	"_ANGUILLA":"Anguilla",
	"_ANTARCTICA":"Antarctica",
	"_ANTIGUA_AND BARBUDA":"Antigua And Barbuda",
	"_ARGENTINA":"Argentina",
	"_ARMENIA":"Armenia",
	"_ARUBA":"Aruba",
	"_AUSTRALIA":"Australia",
	"_AUSTRIA":"Austria",
	"_AZERBAIJAN":"Azerbaijan",
	"_BAHAMAS":"Bahamas",
	"_BAHRAIN":"Bahrain",
	"_BANGLADESH":"Bangladesh",
	"_BARBADOS":"Barbados",
	"_BELARUS":"Belarus",
	"_BELGIUM":"Belgium",
	"_BELIZE":"Belize",
	"_BENIN":"Benin",
	"_BERMUDA":"Bermuda",
	"_BHUTAN":"Bhutan",
	"_BOLIVIA,_PLURINATIONAL STATE OF":"Bolivia",
	"_BOSNIA_AND HERZEGOVINA":"Bosnia And Herzegovina",
	"_BOTSWANA":"Botswana",
	"_BOUVET_ISLAND":"Bouvet Island",
	"_BRAZIL":"Brazil",
	"_BRITISH_INDIAN OCEAN TERRITORY":"British Indian Ocean Territory",
	"_BRUNEI_DARUSSALAM":"Brunei Darussalam",
	"_BULGARIA":"Bulgaria",
	"_BURKINA_FASO":"Burkina Faso",
	"_BURUNDI":"Burundi",
	"_CAMBODIA":"Cambodia",
	"_CAMEROON":"Cameroon",
	"_CANADA":"Canada",
	"_CAPE_VERDE":"Cape Verde",
	"_CAYMAN_ISLANDS":"Cayman Islands",
	"_CENTRAL_AFRICAN REPUBLIC":"Central African Republic",
	"_CHAD":"Chad",
	"_CHILE":"Chile",
	"_CHINA":"China",
	"_CHRISTMAS_ISLAND":"Christmas Island",
	"_COCOS_(KEELING)_ISLANDS":"Cocos Islands",
	"_COLOMBIA":"Colombia",
	"_COMOROS":"Comoros",
	"_CONGO":"Congo",
	"_CONGO,_THE DEMOCRATIC REPUBLIC OF THE":"Congo",
	"_COOK_ISLANDS":"Cook Islands",
	"_COSTA_RICA":"Costa Rica",
	"_CÔTE_D'IVOIRE":"Ivory Coast",
	"_CROATIA":"Croatia",
	"_CUBA":"Cuba",
	"_CYPRUS":"Cyprus",
	"_CZECH_REPUBLIC":"Czech Republic",
	"_DENMARK":"Denmark",
	"_DJIBOUTI":"Djibouti",
	"_DOMINICA":"Dominica",
	"_DOMINICAN_REPUBLIC":"Dominican Republic",
	"_ECUADOR":"Ecuador",
	"_EGYPT":"Egypt",
	"_EL_SALVADOR":"El Salvador",
	"_EQUATORIAL_GUINEA":"Equatorial Guinea",
	"_ERITREA":"Eritrea",
	"_ESTONIA":"Estonia",
	"_ETHIOPIA":"Ethiopia",
	"_FALKLAND_ISLANDS_(MALVINAS)":"Falkland Islands",
	"_FAROE_ISLANDS":"Faroe Islands",
	"_FIJI":"Fiji",
	"_FINLAND":"Finland",
	"_FRANCE":"France",
	"_FRENCH_GUIANA":"French Guiana",
	"_FRENCH_POLYNESIA":"French Polynesia",
	"_FRENCH_SOUTHERN TERRITORIES":"French Southern Territories",
	"_GABON":"Gabon",
	"_GAMBIA":"Gambia",
	"_GEORGIA":"Georgia",
	"_GERMANY":"Germany",
	"_GHANA":"Ghana",
	"_GIBRALTAR":"Gibraltar",
	"_GREECE":"Greece",
	"_GREENLAND":"Greenland",
	"_GRENADA":"Grenada",
	"_GUADELOUPE":"Guadeloupe",
	"_GUAM":"Guam",
	"_GUATEMALA":"Guatemala",
	"_GUERNSEY":"Guernsey",
	"_GUINEA":"Guinea",
	"_GUINEA-BISSAU":"Guinea-Bissau",
	"_GUYANA":"Guyana",
	"_HAITI":"Haiti",
	"_HEARD_ISLAND AND MCDONALD ISLANDS":"Heard Island And Mcdonald Islands",
	"_HONDURAS":"Honduras",
	"_HONG_KONG":"Hong Kong",
	"_HUNGARY":"Hungary",
	"_ICELAND":"Iceland",
	"_INDIA":"India",
	"_INDONESIA":"Indonesia",
	"_IRAN,_ISLAMIC REPUBLIC OF":"Iran",
	"_IRAQ":"Iraq",
	"_IRELAND":"Ireland",
	"_ISLE_OF MAN":"Isle Of Man",
	"_ISRAEL":"Israel",
	"_ITALY":"Italy",
	"_JAMAICA":"Jamaica",
	"_JAPAN":"Japan",
	"_JERSEY":"Jersey",
	"_JORDAN":"Jordan",
	"_KAZAKHSTAN":"Kazakhstan",
	"_KENYA":"Kenya",
	"_KIRIBATI":"Kiribati",
	"_KOREA,_DEMOCRATIC PEOPLE'S REPUBLIC OF":"South Korea",
	"_KOREA,_REPUBLIC OF":"North Korea",
	"_KUWAIT":"Kuwait",
	"_KYRGYZSTAN":"Kyrgyzstan",
	"_LAO_PEOPLE'S DEMOCRATIC REPUBLIC":"Laos",
	"_LATVIA":"Latvia",
	"_LEBANON":"Lebanon",
	"_LESOTHO":"Lesotho",
	"_LIBERIA":"Liberia",
	"_LIBYAN_ARAB JAMAHIRIYA":"Libyan Arab Jamahiriya",
	"_LIECHTENSTEIN":"Liechtenstein",
	"_LITHUANIA":"Lithuania",
	"_LUXEMBOURG":"Luxembourg",
	"_MACAO":"Macao",
	"_MACEDONIA,_THE FORMER YUGOSLAV REPUBLIC OF":"Macedonia",
	"_MADAGASCAR":"Madagascar",
	"_MALAWI":"Malawi",
	"_MALAYSIA":"Malaysia",
	"_MALDIVES":"Maldives",
	"_MALI":"Mali",
	"_MALTA":"Malta",
	"_MARSHALL_ISLANDS":"Marshall Islands",
	"_MARTINIQUE":"Martinique",
	"_MAURITANIA":"Mauritania",
	"_MAURITIUS":"Mauritius",
	"_MAYOTTE":"Mayotte",
	"_MEXICO":"Mexico",
	"_MICRONESIA,_FEDERATED STATES OF":"Micronesia",
	"_MOLDOVA,_REPUBLIC OF":"Moldova",
	"_MONACO":"Monaco",
	"_MONGOLIA":"Mongolia",
	"_MONTENEGRO":"Montenegro",
	"_MONTSERRAT":"Montserrat",
	"_MOROCCO":"Morocco",
	"_MOZAMBIQUE":"Mozambique",
	"_MYANMAR":"Myanmar",
	"_NAMIBIA":"Namibia",
	"_NAURU":"Nauru",
	"_NEPAL":"Nepal",
	"_NETHERLANDS":"Netherlands",
	"_NETHERLANDS_ANTILLES":"Netherlands Antilles",
	"_NEW_CALEDONIA":"New Caledonia",
	"_NEW_ZEALAND":"New Zealand",
	"_NICARAGUA":"Nicaragua",
	"_NIGER":"Niger",
	"_NIGERIA":"Nigeria",
	"_NIUE":"Niue",
	"_NORFOLK_ISLAND":"Norfolk Island",
	"_NORTHERN_MARIANA ISLANDS":"Northern Mariana Islands",
	"_NORWAY":"Norway",
	"_OMAN":"Oman",
	"_PAKISTAN":"Pakistan",
	"_PALAU":"Palau",
	"_PALESTINIAN_TERRITORY, OCCUPIED":"Palestine",
	"_PANAMA":"Panama",
	"_PAPUA_NEW GUINEA":"Papua New Guinea",
	"_PARAGUAY":"Paraguay",
	"_PERU":"Peru",
	"_PHILIPPINES":"Philippines",
	"_PITCAIRN":"Pitcairn",
	"_POLAND":"Poland",
	"_PORTUGAL":"Portugal",
	"_PUERTO_RICO":"Puerto Rico",
	"_QATAR":"Qatar",
	"_RÉUNION":"RÉUnion",
	"_ROMANIA":"Romania",
	"_RUSSIAN_FEDERATION":"Russian Federation",
	"_RWANDA":"Rwanda",
	"_SAINT_BARTHÉLEMY":"Saint BarthÉLemy",
	"_SAINT_HELENA, ASCENSION AND TRISTAN DA CUNHA":"Saint Helena, Ascension And Tristan Da Cunha",
	"_TTS_AND NEVIS":"Tts And Nevis",
	"_SAINT_LUCIA":"Saint Lucia",
	"_SAINT_MARTIN":"Saint Martin",
	"_SAINT_PIERRE AND MIQUELON":"Saint Pierre And Miquelon",
	"_SAINT_VINCENT AND THE GRENADINES":"Saint Vincent And The Grenadines",
	"_SAMOA":"Samoa",
	"_SAN_MARINO":"San Marino",
	"_SAO_TOME AND PRINCIPE":"Sao Tome And Principe",
	"_SAUDI_ARABIA":"Saudi Arabia",
	"_SENEGAL":"Senegal",
	"_SERBIA":"Serbia",
	"_SEYCHELLES":"Seychelles",
	"_SIERRA_LEONE":"Sierra Leone",
	"_SINGAPORE":"Singapore",
	"_SLOVAKIA":"Slovakia",
	"_SLOVENIA":"Slovenia",
	"_SOLOMON_ISLANDS":"Solomon Islands",
	"_SOMALIA":"Somalia",
	"_SOUTH_AFRICA":"South Africa",
	"_SOUTH_GEORGIA AND THE SOUTH SANDWICH ISLANDS":"South Georgia And The South Sandwich Islands",
	"_SPAIN":"Spain",
	"_SRI_LANKA":"Sri Lanka",
	"_SUDAN":"Sudan",
	"_SURINAME":"Suriname",
	"_SVALBARD_AND JAN MAYEN":"Svalbard And Jan Mayen",
	"_SWAZILAND":"Swaziland",
	"_SWEDEN":"Sweden",
	"_SWITZERLAND":"Switzerland",
	"_SYRIAN_ARAB REPUBLIC":"Syrian Arab Republic",
	"_TAIWAN,_PROVINCE OF CHINA":"Taiwan",
	"_TAJIKISTAN":"Tajikistan",
	"_TANZANIA,_UNITED REPUBLIC OF":"Tanzania",
	"_THAILAND":"Thailand",
	"_TIMOR-LESTE":"Timor-Leste",
	"_TOGO":"Togo",
	"_TOKELAU":"Tokelau",
	"_TONGA":"Tonga",
	"_TRINIDAD_AND TOBAGO":"Trinidad And Tobago",
	"_TUNISIA":"Tunisia",
	"_TURKEY":"Turkey",
	"_TURKMENISTAN":"Turkmenistan",
	"_TURKS_AND CAICOS ISLANDS":"Turks And Caicos Islands",
	"_TUVALU":"Tuvalu",
	"_UGANDA":"Uganda",
	"_UKRAINE":"Ukraine",
	"_UNITED_ARAB EMIRATES":"United Arab Emirates",
	"_UNITED_KINGDOM":"United Kingdom",
	"_UNITED_STATES":"United States",
	"_UNITED_STATES MINOR OUTLYING ISLANDS":"United States Minor Outlying Islands",
	"_URUGUAY":"Uruguay",
	"_UZBEKISTAN":"Uzbekistan",
	"_VANUATU":"Vanuatu",
	"_VATICAN_CITY STATE":"Vatican City",
	"_VENEZUELA,_BOLIVARIAN REPUBLIC OF":"Venezuela",
	"_VIET_NAM":"Viet Nam",
	"_VIRGIN_ISLANDS, BRITISH":"Virgin Islands, British",
	"_VIRGIN_ISLANDS, U.S.":"Virgin Islands, U.S.",
	"_WALLIS_AND FUTUNA":"Wallis And Futuna",
	"_WESTERN_SAHARA":"Western Sahara",
	"_YEMEN":"Yemen",
	"_ZAMBIA":"Zambia",
	"_ZIMBABWE":"Zimbabwe",
	"_SOUTHERN_SUDAN_TERRITORY,_PROVISIONAL":"Southern Sudan",
	
	// Activities
	"_Agriculture":"Agriculture",
	"_Air Conditioning":"Air Conditioning",
	"_Animal Sales":"Animal Sales",
	"_Arts":"Arts",
	"_Auto Repair":"Auto Repair",
	"_Bakery":"Bakery",
	"_Balut-Making":"Balut-Making",
	"_Barber Shop":"Barber Shop",
	"_Beauty Salon":"Beauty Salon",
	"_Bicycle Repair":"Bicycle Repair",
	"_Bicycle Sales":"Bicycle Sales",
	"_Biofuels":"Biofuels",
	"_Blacksmith":"Blacksmith",
	"_Bookbinding":"Bookbinding",
	"_Bookstore":"Bookstore",
	"_Bricks":"Bricks",
	"_Butcher Shop":"Butcher Shop",
	"_Cafe":"Cafe",
	"_Call Center":"Call Center",
	"_Carpentry":"Carpentry",
	"_Catering":"Catering",
	"_Cattle":"Cattle",
	"_Cement":"Cement",
	"_Cereals":"Cereals",
	"_Charcoal Sales":"Charcoal Sales",
	"_Cheese Making":"Cheese Making",
	"_Child Care":"Child Care",
	"_Cloth & Dressmaking Supplies":"Cloth & Dressmaking Supplies",
	"_Clothing":"Clothing",
	"_Clothing Sales":"Clothing Sales",
	"_Cobbler":"Cobbler",
	"_Computers":"Computers",
	"_Construction":"Construction",
	"_Construction Supplies":"Construction Supplies",
	"_Consumer Goods":"Consumer Goods",
	"_Cosmetics Sales":"Cosmetics Sales",
	"_Crafts":"Crafts",
	"_Dairy":"Dairy",
	"_Decorations Sales":"Decorations Sales",
	"_Dental":"Dental",
	"_Electrical Goods":"Electrical Goods",
	"_Electrician":"Electrician",
	"_Electronics Repair":"Electronics Repair",
	"_Electronics Sales":"Electronics Sales",
	"_Embroidery":"Embroidery",
	"_Energy Efficiency":"Energy Efficiency",
	"_Entertainment":"Entertainment",
	"_Farm Supplies":"Farm Supplies",
	"_Farming":"Farming",
	"_Film":"Film",
	"_Fish Selling":"Fish Selling",
	"_Fishing":"Fishing",
	"_Flowers":"Flowers",
	"_Food":"Food",
	"_Food Market":"Food Market",
	"_Food Production/Sales":"Food Production/Sales",
	"_Food Stall":"Food Stall",
	"_Fruits & Vegetables":"Fruits & Vegetables",
	"_Fuel/Firewood":"Fuel/Firewood",
	"_Funeral Expenses":"Funeral Expenses",
	"_Furniture Making":"Furniture Making",
	"_Games":"Games",
	"_General Store":"General Store",
	"_Goods Distribution":"Goods Distribution",
	"_Green":"Green",
	"_Grocery Store":"Grocery Store",
	"_Hardware":"Hardware",
	"_Health":"Health",
	"_Home Appliances":"Home Appliances",
	"_Home Products Sales":"Home Products Sales",
	"_Hotel":"Hotel",
	"_Internet Cafe":"Internet Cafe",
	"_Jewelry":"Jewelry",
	"_Knitting":"Knitting",
	"_Land Rental":"Land Rental",
	"_Laundry":"Laundry",
	"_Liquor Store / Off-License":"Liquor Store / Off-License",
	"_Livestock":"Livestock",
	"_Machine Shop":"Machine Shop",
	"_Machinery Rental":"Machinery Rental",
	"_Manufacturing":"Manufacturing",
	"_Medical Clinic":"Medical Clinic",
	"_Metal Shop":"Metal Shop",
	"_Milk Sales":"Milk Sales",
	"_Mobile Phones":"Mobile Phones",
	"_Motorcycle Repair":"Motorcycle Repair",
	"_Motorcycle Transport":"Motorcycle Transport",
	"_Movie Tapes and DVDs":"Movie Tapes and DVDs",
	"_Music Discs and Tapes":"Music Discs and Tapes",
	"_Musical Instruments":"Musical Instruments",
	"_Musical Performance":"Musical Performance",
	"_Natural Medicines":"Natural Medicines",
	"_Office Supplies":"Office Supplies",
	"_Paper Sales":"Paper Sales",
	"_Party Supplies":"Party Supplies",
	"_Patchwork":"Patchwork",
	"_Perfumes":"Perfumes",
	"_Personal Education Expenses":"Personal Education Expenses",
	"_Personal Housing Expenses":"Personal Housing Expenses",
	"_Personal Medical Expenses":"Personal Medical Expenses",
	"_Personal Products Sales":"Personal Products Sales",
	"_Personal Purchases":"Personal Purchases",
	"_Pharmacy":"Pharmacy",
	"_Phone Accessories":"Phone Accessories",
	"_Phone Repair":"Phone Repair",
	"_Phone Use Sales":"Phone Use Sales",
	"_Photography":"Photography",
	"_Pigs":"Pigs",
	"_Plastics Sales":"Plastics Sales",
	"_Poultry":"Poultry",
	"_Printing":"Printing",
	"_Property":"Property",
	"_Pub":"Pub",
	"_Quarrying":"Quarrying",
	"_Recycling":"Recycling",
	"_Religious Articles":"Religious Articles",
	"_Restaurant":"Restaurant",
	"_Retail":"Retail",
	"_Rickshaw":"Rickshaw",
	"_Secretarial Services":"Secretarial Services",
	"_Services":"Services",
	"_Sewing":"Sewing",
	"_Shoe Sales":"Shoe Sales",
	"_Soft Drinks":"Soft Drinks",
	"_Solar Power":"Solar Power",
	"_Souvenir Sales":"Souvenir Sales",
	"_Spare Parts":"Spare Parts",
	"_Sporting Good Sales":"Sporting Good Sales",
	"_Tailoring":"Tailoring",
	"_Taxi":"Taxi",
	"_Teaching and Schools":"Teaching and Schools",
	"_Textiles":"Textiles",
	"_Timber Sales":"Timber Sales",
	"_Tourism":"Tourism",
	"_Transportation":"Transportation",
	"_Traveling Sales":"Traveling Sales",
	"_Upholstery":"Upholstery",
	"_Used Clothing":"Used Clothing",
	"_Utilities":"Utilities",
	"_Vehicle":"Vehicle",
	"_Vehicle Repairs":"Vehicle Repairs",
	"_Veterinary Sales":"Veterinary Sales",
	"_Waste Management":"Waste Management",
	"_Water Distribution":"Water Distribution",
	"_Weaving":"Weaving",
	"_Wedding Expenses":"Wedding Expenses",
	"_Well digging":"Well digging",
	"_Wholesale":"Wholesale",
	
	// Sectors
	"_Agriculture":"Agriculture",
	"_Arts":"Arts",
	"_Clothing":"Clothing",
	"_Construction":"Construction",
	"_Education":"Education",
	"_Entertainment":"Entertainment",
	"_Food":"Food",
	"_Green":"Green",
	"_Health":"Health",
	"_Housing":"Housing",
	"_Manufacturing":"Manufacturing",
	"_Personal_Use":"Personal Use",
	"_Retail":"Retail",
	"_Services":"Services",
	"_Transportation":"Transportation",
	"_Wholesale":"Wholesale",
	
	// ABOUT
	"_What_is_Kiva?":"What is Kiva?",
	"*aboutContent": '<p>Kiva‘s mission is to connect people, through lending, for the sake of alleviating poverty.</p>\n\n<p>Kiva empowers individuals to lend to an entrepreneur across the globe. By combining microfinance with the internet, Kiva is creating a global community of people connected through lending.</p>\n\n<div class=\'kiva-figureRight\'>\n	    		<a  href="http://www.kiva.org/lend/23303" target="_blank" ><img  border="0" src="http://www.kiva.org/images/Pendo.jpg" class="scaled" /></a>\n\n<p><a href="http://www.kiva.org/lend/23303">Pendo Luisi</a>, 27 years old, borrowed $175 to open a cafe in Dar es Salaam, Tanzania.</p>\n  </div>\n\n<p>Kiva was born of the following beliefs:\n<ul>\n<li>People are by nature generous, and will help others if given the opportunity to do so in a transparent, accountable way.</li>\n<li>The poor are highly motivated and can be very successful when given an opportunity.</li>\n<li>By connecting people we can create relationships beyond financial transactions, and build a global community expressing support and encouragement of one another.</li>\n</ul>\n</p>\n\n<p>Kiva promotes:\n<ul>\n<li>Dignity: &nbsp; Kiva encourages partnership relationships as opposed to benefactor relationships. Partnership relationships are characterized by mutual dignity and respect.</li>\n<li>Accountability: &nbsp; Loans encourage more accountability than donations where repayment is not expected.</li><br/>\n<li>Transparency: &nbsp; The Kiva website is an open platform where communication can flow freely around the world.</li>\n</ul>\n</p>\n\n<p>As of November 2009, Kiva has facilitated over $100 million in loans.</p>',
}) ;
